/*
Synctera API

This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: 0.153.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the PatchPersonBusinessOwnerRelationship type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchPersonBusinessOwnerRelationship{}

// PatchPersonBusinessOwnerRelationship Denotes the relationship between specified business and person.
type PatchPersonBusinessOwnerRelationship struct {
	AdditionalData *AdditionalOwnerData `json:"additional_data,omitempty"`
	// The date and time the resource was created.
	CreationTime *time.Time `json:"creation_time,omitempty"`
	// Unique ID for the subject person.
	FromPersonId *string `json:"from_person_id,omitempty"`
	// Relationship unique identifier.
	Id *string `json:"id,omitempty"`
	// The date and time the resource was last updated.
	LastUpdatedTime *time.Time `json:"last_updated_time,omitempty"`
	// Optional field to store additional information about the resource. Intended to be used by the integrator to store non-sensitive data.
	Metadata         map[string]interface{} `json:"metadata,omitempty"`
	RelationshipType RelationshipTypes      `json:"relationship_type"`
	// The id of the tenant containing the resource. This is relevant for Fintechs that have multiple workspaces.
	Tenant *string `json:"tenant,omitempty"`
	// Unique ID for the related business.
	ToBusinessId *string `json:"to_business_id,omitempty"`
}

type _PatchPersonBusinessOwnerRelationship PatchPersonBusinessOwnerRelationship

// NewPatchPersonBusinessOwnerRelationship instantiates a new PatchPersonBusinessOwnerRelationship object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchPersonBusinessOwnerRelationship(relationshipType RelationshipTypes) *PatchPersonBusinessOwnerRelationship {
	this := PatchPersonBusinessOwnerRelationship{}
	this.RelationshipType = relationshipType
	return &this
}

// NewPatchPersonBusinessOwnerRelationshipWithDefaults instantiates a new PatchPersonBusinessOwnerRelationship object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchPersonBusinessOwnerRelationshipWithDefaults() *PatchPersonBusinessOwnerRelationship {
	this := PatchPersonBusinessOwnerRelationship{}
	return &this
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *PatchPersonBusinessOwnerRelationship) GetAdditionalData() AdditionalOwnerData {
	if o == nil || IsNil(o.AdditionalData) {
		var ret AdditionalOwnerData
		return ret
	}
	return *o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchPersonBusinessOwnerRelationship) GetAdditionalDataOk() (*AdditionalOwnerData, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return nil, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *PatchPersonBusinessOwnerRelationship) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given AdditionalOwnerData and assigns it to the AdditionalData field.
func (o *PatchPersonBusinessOwnerRelationship) SetAdditionalData(v AdditionalOwnerData) {
	o.AdditionalData = &v
}

// GetCreationTime returns the CreationTime field value if set, zero value otherwise.
func (o *PatchPersonBusinessOwnerRelationship) GetCreationTime() time.Time {
	if o == nil || IsNil(o.CreationTime) {
		var ret time.Time
		return ret
	}
	return *o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchPersonBusinessOwnerRelationship) GetCreationTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreationTime) {
		return nil, false
	}
	return o.CreationTime, true
}

// HasCreationTime returns a boolean if a field has been set.
func (o *PatchPersonBusinessOwnerRelationship) HasCreationTime() bool {
	if o != nil && !IsNil(o.CreationTime) {
		return true
	}

	return false
}

// SetCreationTime gets a reference to the given time.Time and assigns it to the CreationTime field.
func (o *PatchPersonBusinessOwnerRelationship) SetCreationTime(v time.Time) {
	o.CreationTime = &v
}

// GetFromPersonId returns the FromPersonId field value if set, zero value otherwise.
func (o *PatchPersonBusinessOwnerRelationship) GetFromPersonId() string {
	if o == nil || IsNil(o.FromPersonId) {
		var ret string
		return ret
	}
	return *o.FromPersonId
}

// GetFromPersonIdOk returns a tuple with the FromPersonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchPersonBusinessOwnerRelationship) GetFromPersonIdOk() (*string, bool) {
	if o == nil || IsNil(o.FromPersonId) {
		return nil, false
	}
	return o.FromPersonId, true
}

// HasFromPersonId returns a boolean if a field has been set.
func (o *PatchPersonBusinessOwnerRelationship) HasFromPersonId() bool {
	if o != nil && !IsNil(o.FromPersonId) {
		return true
	}

	return false
}

// SetFromPersonId gets a reference to the given string and assigns it to the FromPersonId field.
func (o *PatchPersonBusinessOwnerRelationship) SetFromPersonId(v string) {
	o.FromPersonId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PatchPersonBusinessOwnerRelationship) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchPersonBusinessOwnerRelationship) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PatchPersonBusinessOwnerRelationship) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PatchPersonBusinessOwnerRelationship) SetId(v string) {
	o.Id = &v
}

// GetLastUpdatedTime returns the LastUpdatedTime field value if set, zero value otherwise.
func (o *PatchPersonBusinessOwnerRelationship) GetLastUpdatedTime() time.Time {
	if o == nil || IsNil(o.LastUpdatedTime) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdatedTime
}

// GetLastUpdatedTimeOk returns a tuple with the LastUpdatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchPersonBusinessOwnerRelationship) GetLastUpdatedTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUpdatedTime) {
		return nil, false
	}
	return o.LastUpdatedTime, true
}

// HasLastUpdatedTime returns a boolean if a field has been set.
func (o *PatchPersonBusinessOwnerRelationship) HasLastUpdatedTime() bool {
	if o != nil && !IsNil(o.LastUpdatedTime) {
		return true
	}

	return false
}

// SetLastUpdatedTime gets a reference to the given time.Time and assigns it to the LastUpdatedTime field.
func (o *PatchPersonBusinessOwnerRelationship) SetLastUpdatedTime(v time.Time) {
	o.LastUpdatedTime = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *PatchPersonBusinessOwnerRelationship) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchPersonBusinessOwnerRelationship) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PatchPersonBusinessOwnerRelationship) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *PatchPersonBusinessOwnerRelationship) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetRelationshipType returns the RelationshipType field value
func (o *PatchPersonBusinessOwnerRelationship) GetRelationshipType() RelationshipTypes {
	if o == nil {
		var ret RelationshipTypes
		return ret
	}

	return o.RelationshipType
}

// GetRelationshipTypeOk returns a tuple with the RelationshipType field value
// and a boolean to check if the value has been set.
func (o *PatchPersonBusinessOwnerRelationship) GetRelationshipTypeOk() (*RelationshipTypes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RelationshipType, true
}

// SetRelationshipType sets field value
func (o *PatchPersonBusinessOwnerRelationship) SetRelationshipType(v RelationshipTypes) {
	o.RelationshipType = v
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *PatchPersonBusinessOwnerRelationship) GetTenant() string {
	if o == nil || IsNil(o.Tenant) {
		var ret string
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchPersonBusinessOwnerRelationship) GetTenantOk() (*string, bool) {
	if o == nil || IsNil(o.Tenant) {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *PatchPersonBusinessOwnerRelationship) HasTenant() bool {
	if o != nil && !IsNil(o.Tenant) {
		return true
	}

	return false
}

// SetTenant gets a reference to the given string and assigns it to the Tenant field.
func (o *PatchPersonBusinessOwnerRelationship) SetTenant(v string) {
	o.Tenant = &v
}

// GetToBusinessId returns the ToBusinessId field value if set, zero value otherwise.
func (o *PatchPersonBusinessOwnerRelationship) GetToBusinessId() string {
	if o == nil || IsNil(o.ToBusinessId) {
		var ret string
		return ret
	}
	return *o.ToBusinessId
}

// GetToBusinessIdOk returns a tuple with the ToBusinessId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchPersonBusinessOwnerRelationship) GetToBusinessIdOk() (*string, bool) {
	if o == nil || IsNil(o.ToBusinessId) {
		return nil, false
	}
	return o.ToBusinessId, true
}

// HasToBusinessId returns a boolean if a field has been set.
func (o *PatchPersonBusinessOwnerRelationship) HasToBusinessId() bool {
	if o != nil && !IsNil(o.ToBusinessId) {
		return true
	}

	return false
}

// SetToBusinessId gets a reference to the given string and assigns it to the ToBusinessId field.
func (o *PatchPersonBusinessOwnerRelationship) SetToBusinessId(v string) {
	o.ToBusinessId = &v
}

func (o PatchPersonBusinessOwnerRelationship) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchPersonBusinessOwnerRelationship) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdditionalData) {
		toSerialize["additional_data"] = o.AdditionalData
	}
	if !IsNil(o.CreationTime) {
		toSerialize["creation_time"] = o.CreationTime
	}
	if !IsNil(o.FromPersonId) {
		toSerialize["from_person_id"] = o.FromPersonId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LastUpdatedTime) {
		toSerialize["last_updated_time"] = o.LastUpdatedTime
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["relationship_type"] = o.RelationshipType
	if !IsNil(o.Tenant) {
		toSerialize["tenant"] = o.Tenant
	}
	if !IsNil(o.ToBusinessId) {
		toSerialize["to_business_id"] = o.ToBusinessId
	}
	return toSerialize, nil
}

func (o *PatchPersonBusinessOwnerRelationship) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"relationship_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPatchPersonBusinessOwnerRelationship := _PatchPersonBusinessOwnerRelationship{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPatchPersonBusinessOwnerRelationship)

	if err != nil {
		return err
	}

	*o = PatchPersonBusinessOwnerRelationship(varPatchPersonBusinessOwnerRelationship)

	return err
}

type NullablePatchPersonBusinessOwnerRelationship struct {
	value *PatchPersonBusinessOwnerRelationship
	isSet bool
}

func (v NullablePatchPersonBusinessOwnerRelationship) Get() *PatchPersonBusinessOwnerRelationship {
	return v.value
}

func (v *NullablePatchPersonBusinessOwnerRelationship) Set(val *PatchPersonBusinessOwnerRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchPersonBusinessOwnerRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchPersonBusinessOwnerRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchPersonBusinessOwnerRelationship(val *PatchPersonBusinessOwnerRelationship) *NullablePatchPersonBusinessOwnerRelationship {
	return &NullablePatchPersonBusinessOwnerRelationship{value: val, isSet: true}
}

func (v NullablePatchPersonBusinessOwnerRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchPersonBusinessOwnerRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
