/*
Synctera API

This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: 0.150.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AddressesList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddressesList{}

// AddressesList struct for AddressesList
type AddressesList struct {
	// If returned, use the next_page_token to query for the next page of results. Not returned if there are no more rows.
	NextPageToken *string `json:"next_page_token,omitempty"`
	// Array of Addresses
	Addresses []AddressResponse `json:"addresses"`
}

type _AddressesList AddressesList

// NewAddressesList instantiates a new AddressesList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressesList(addresses []AddressResponse) *AddressesList {
	this := AddressesList{}
	this.Addresses = addresses
	return &this
}

// NewAddressesListWithDefaults instantiates a new AddressesList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressesListWithDefaults() *AddressesList {
	this := AddressesList{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *AddressesList) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressesList) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *AddressesList) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *AddressesList) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetAddresses returns the Addresses field value
func (o *AddressesList) GetAddresses() []AddressResponse {
	if o == nil {
		var ret []AddressResponse
		return ret
	}

	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value
// and a boolean to check if the value has been set.
func (o *AddressesList) GetAddressesOk() ([]AddressResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Addresses, true
}

// SetAddresses sets field value
func (o *AddressesList) SetAddresses(v []AddressResponse) {
	o.Addresses = v
}

func (o AddressesList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddressesList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextPageToken) {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	toSerialize["addresses"] = o.Addresses
	return toSerialize, nil
}

func (o *AddressesList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"addresses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddressesList := _AddressesList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddressesList)

	if err != nil {
		return err
	}

	*o = AddressesList(varAddressesList)

	return err
}

type NullableAddressesList struct {
	value *AddressesList
	isSet bool
}

func (v NullableAddressesList) Get() *AddressesList {
	return v.value
}

func (v *NullableAddressesList) Set(val *AddressesList) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressesList) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressesList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressesList(val *AddressesList) *NullableAddressesList {
	return &NullableAddressesList{value: val, isSet: true}
}

func (v NullableAddressesList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressesList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
