/*
 * Synctera API
 *
 * <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p> 
 *
 * API version: 0.17.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type AccountSummary struct {
	// Account number
	AccountNumber string `json:"account_number,omitempty"`
	// Account Status
	AccountStatus string `json:"account_status,omitempty"`
	// The type of the account. In lead mode, this always takes the value of the template. If not specified in shadow mode, CHECKING will be assumed. 
	AccountType string `json:"account_type,omitempty"`
	BalanceCeiling *AccountSummaryBalanceCeiling `json:"balance_ceiling,omitempty"`
	BalanceFloor *AccountSummaryBalanceFloor `json:"balance_floor,omitempty"`
	// Account creation time
	CreationTime time.Time `json:"creation_time,omitempty"`
	// Account currency or account settlement currency. ISO 4217 alphabetic currency code. Default USD
	Currency string `json:"currency,omitempty"`
	// Customer type
	CustomerType string `json:"customer_type,omitempty"`
	FinancialInstitution *FinancialInstitution `json:"financial_institution,omitempty"`
	// The unique identifier of the account the statement belongs to
	Id string `json:"id,omitempty"`
	// Account last modification time
	LastUpdatedTime time.Time `json:"last_updated_time,omitempty"`
	// User provided account nickname
	Nickname string `json:"nickname,omitempty"`
}
