/*
Synctera API

This is the official reference documentation for Synctera APIs. If you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact-us' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: 0.140.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GatewayPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayPatch{}

// GatewayPatch Gateway Config Update Request
type GatewayPatch struct {
	// Custom http headers for the Auth request to Gateway URL
	CustomHeaders map[string][]string `json:"custom_headers,omitempty"`
	// Allows to disable/enable Gateway Config for the Fintech (Tenant)
	Disabled *bool `json:"disabled,omitempty"`
	// Maximum amount of time in milliseconds that we will wait for the response from Gateway URL request
	MaxWaitMs *int32 `json:"max_wait_ms,omitempty"`
	// The URL address which will be used for the ACH in Auth Flow requests to get authorization from the fintech to process the transaction
	Url *string `json:"url,omitempty"`
}

// NewGatewayPatch instantiates a new GatewayPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayPatch() *GatewayPatch {
	this := GatewayPatch{}
	return &this
}

// NewGatewayPatchWithDefaults instantiates a new GatewayPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayPatchWithDefaults() *GatewayPatch {
	this := GatewayPatch{}
	return &this
}

// GetCustomHeaders returns the CustomHeaders field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GatewayPatch) GetCustomHeaders() map[string][]string {
	if o == nil {
		var ret map[string][]string
		return ret
	}
	return o.CustomHeaders
}

// GetCustomHeadersOk returns a tuple with the CustomHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GatewayPatch) GetCustomHeadersOk() (*map[string][]string, bool) {
	if o == nil || IsNil(o.CustomHeaders) {
		return nil, false
	}
	return &o.CustomHeaders, true
}

// HasCustomHeaders returns a boolean if a field has been set.
func (o *GatewayPatch) HasCustomHeaders() bool {
	if o != nil && !IsNil(o.CustomHeaders) {
		return true
	}

	return false
}

// SetCustomHeaders gets a reference to the given map[string][]string and assigns it to the CustomHeaders field.
func (o *GatewayPatch) SetCustomHeaders(v map[string][]string) {
	o.CustomHeaders = v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *GatewayPatch) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatch) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *GatewayPatch) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *GatewayPatch) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetMaxWaitMs returns the MaxWaitMs field value if set, zero value otherwise.
func (o *GatewayPatch) GetMaxWaitMs() int32 {
	if o == nil || IsNil(o.MaxWaitMs) {
		var ret int32
		return ret
	}
	return *o.MaxWaitMs
}

// GetMaxWaitMsOk returns a tuple with the MaxWaitMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatch) GetMaxWaitMsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxWaitMs) {
		return nil, false
	}
	return o.MaxWaitMs, true
}

// HasMaxWaitMs returns a boolean if a field has been set.
func (o *GatewayPatch) HasMaxWaitMs() bool {
	if o != nil && !IsNil(o.MaxWaitMs) {
		return true
	}

	return false
}

// SetMaxWaitMs gets a reference to the given int32 and assigns it to the MaxWaitMs field.
func (o *GatewayPatch) SetMaxWaitMs(v int32) {
	o.MaxWaitMs = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *GatewayPatch) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPatch) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *GatewayPatch) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *GatewayPatch) SetUrl(v string) {
	o.Url = &v
}

func (o GatewayPatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CustomHeaders != nil {
		toSerialize["custom_headers"] = o.CustomHeaders
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if !IsNil(o.MaxWaitMs) {
		toSerialize["max_wait_ms"] = o.MaxWaitMs
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableGatewayPatch struct {
	value *GatewayPatch
	isSet bool
}

func (v NullableGatewayPatch) Get() *GatewayPatch {
	return v.value
}

func (v *NullableGatewayPatch) Set(val *GatewayPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayPatch(val *GatewayPatch) *NullableGatewayPatch {
	return &NullableGatewayPatch{value: val, isSet: true}
}

func (v NullableGatewayPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
