/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
)

// CardActionState the model 'CardActionState'
type CardActionState string

// List of card_action_state
const (
	CARDACTIONSTATE_ACCEPT                  CardActionState = "ACCEPT"
	CARDACTIONSTATE_CREATE                  CardActionState = "CREATE"
	CARDACTIONSTATE_LOST                    CardActionState = "LOST"
	CARDACTIONSTATE_NETWORK_REJECT          CardActionState = "NETWORK_REJECT"
	CARDACTIONSTATE_NETWORK_REJECT_REVERSAL CardActionState = "NETWORK_REJECT_REVERSAL"
	CARDACTIONSTATE_REBUT                   CardActionState = "REBUT"
	CARDACTIONSTATE_REVERSE                 CardActionState = "REVERSE"
	CARDACTIONSTATE_WON                     CardActionState = "WON"
)

// All allowed values of CardActionState enum
var AllowedCardActionStateEnumValues = []CardActionState{
	"ACCEPT",
	"CREATE",
	"LOST",
	"NETWORK_REJECT",
	"NETWORK_REJECT_REVERSAL",
	"REBUT",
	"REVERSE",
	"WON",
}

func (v *CardActionState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CardActionState(value)
	for _, existing := range AllowedCardActionStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CardActionState", value)
}

// NewCardActionStateFromValue returns a pointer to a valid CardActionState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCardActionStateFromValue(v string) (*CardActionState, error) {
	ev := CardActionState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CardActionState: valid values are %v", v, AllowedCardActionStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CardActionState) IsValid() bool {
	for _, existing := range AllowedCardActionStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to card_action_state value
func (v CardActionState) Ptr() *CardActionState {
	return &v
}

type NullableCardActionState struct {
	value *CardActionState
	isSet bool
}

func (v NullableCardActionState) Get() *CardActionState {
	return v.value
}

func (v *NullableCardActionState) Set(val *CardActionState) {
	v.value = val
	v.isSet = true
}

func (v NullableCardActionState) IsSet() bool {
	return v.isSet
}

func (v *NullableCardActionState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardActionState(val *CardActionState) *NullableCardActionState {
	return &NullableCardActionState{value: val, isSet: true}
}

func (v NullableCardActionState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardActionState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
