/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the IncomingWire type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IncomingWire{}

// IncomingWire struct for IncomingWire
type IncomingWire struct {
	// Transfer amount in cents ($100 would be 10000)
	Amount int32 `json:"amount"`
	// Information from the sending bank to the receiving bank.
	BankMessage  *string   `json:"bank_message,omitempty"`
	CreationTime time.Time `json:"creation_time"`
	// 3-character currency code
	Currency *string `json:"currency,omitempty"`
	// The customer UUID representing the person initiating the Wire transfer
	CustomerId *string `json:"customer_id,omitempty"`
	// Description of any errors or problems encountered during processing.
	DeclineReason *string `json:"decline_reason,omitempty"`
	// The effective date of the transaction
	EffectiveDate *string `json:"effective_date,omitempty"`
	// A mandatory reference assigned by the customer originating the payment, i.e., Debtor or Ultimate Debtor that must be transported unchanged throughout the payment chain and delivered to the end-customer, i.e., Creditor or Ultimate Creditor to facilitate the customer’s reconciliation.
	EndToEndIdentification *string `json:"end_to_end_identification,omitempty"`
	// wire ID
	Id string `json:"id"`
	// The IMAD of the incoming wire. The field is called Message Identification in the ISO format.
	InputMessageAccountabilityData *string `json:"input_message_accountability_data,omitempty"`
	// An optional reference that the Fedwire Funds participant sending the message may include in a customer credit transfers sent across the Fedwire Funds Service and will be delivered unchanged to the Fedwire Funds participant receiving the message.
	InstructionIdentification *string `json:"instruction_identification,omitempty"`
	// Indicates if the wire is a return of an outgoing wire
	IsReturn bool `json:"is_return"`
	// The network used to process the wire
	Network *string `json:"network,omitempty"`
	// The account number of the sender, as provided in the wire file.
	OriginatingAccountNumber *string `json:"originating_account_number,omitempty"`
	Receiver                 Party   `json:"receiver"`
	// The internal Synctera account uuid representing the recipient of the wire.
	ReceivingAccountId *string `json:"receiving_account_id,omitempty"`
	// The account number of the recipient, as provided in the wire file.
	ReceivingAccountNumber string `json:"receiving_account_number"`
	// Information from the originator to the beneficiary (recipient).
	RecipientMessage *string     `json:"recipient_message,omitempty"`
	ReturnData       *ReturnData `json:"return_data,omitempty"`
	// The reason we are returning this wire.
	ReturnReason *string `json:"return_reason,omitempty"`
	Sender       Party   `json:"sender"`
	// Sender's id associated with fedwire transfer
	SenderReferenceId string `json:"sender_reference_id"`
	// The settlement date of the transaction
	SettlementDate *string `json:"settlement_date,omitempty"`
	// The current status of the transfer
	Status string `json:"status"`
	// The id of the tenant containing the resource.
	Tenant string `json:"tenant"`
	// ID of the resulting transaction resource
	TransactionId *string `json:"transaction_id,omitempty"`
	// An optional reference that the first financial institution in the end-to-end payment chain may assign to the customer credit transfer and that should remain unchanged throughout the end-to-end funds-transfer chain of financial institutions.
	TransactionIdentification *string `json:"transaction_identification,omitempty"`
	// The fedwire label associated with the subtype code
	TypeSubtype *string `json:"type_subtype,omitempty"`
	// Unique End-To-End Reference (UETR) is a mandatory reference in line with the Universally Unique Identifier (UUID) version 4 standard. The UETR is used to facilitate end-to-end payments tracking.
	Uetr                 *string `json:"uetr,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IncomingWire IncomingWire

// NewIncomingWire instantiates a new IncomingWire object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncomingWire(amount int32, creationTime time.Time, id string, isReturn bool, receiver Party, receivingAccountNumber string, sender Party, senderReferenceId string, status string, tenant string) *IncomingWire {
	this := IncomingWire{}
	this.Amount = amount
	this.CreationTime = creationTime
	this.Id = id
	this.IsReturn = isReturn
	this.Receiver = receiver
	this.ReceivingAccountNumber = receivingAccountNumber
	this.Sender = sender
	this.SenderReferenceId = senderReferenceId
	this.Status = status
	this.Tenant = tenant
	return &this
}

// NewIncomingWireWithDefaults instantiates a new IncomingWire object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncomingWireWithDefaults() *IncomingWire {
	this := IncomingWire{}
	return &this
}

// GetAmount returns the Amount field value
func (o *IncomingWire) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *IncomingWire) SetAmount(v int32) {
	o.Amount = v
}

// GetBankMessage returns the BankMessage field value if set, zero value otherwise.
func (o *IncomingWire) GetBankMessage() string {
	if o == nil || IsNil(o.BankMessage) {
		var ret string
		return ret
	}
	return *o.BankMessage
}

// GetBankMessageOk returns a tuple with the BankMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetBankMessageOk() (*string, bool) {
	if o == nil || IsNil(o.BankMessage) {
		return nil, false
	}
	return o.BankMessage, true
}

// HasBankMessage returns a boolean if a field has been set.
func (o *IncomingWire) HasBankMessage() bool {
	if o != nil && !IsNil(o.BankMessage) {
		return true
	}

	return false
}

// SetBankMessage gets a reference to the given string and assigns it to the BankMessage field.
func (o *IncomingWire) SetBankMessage(v string) {
	o.BankMessage = &v
}

// GetCreationTime returns the CreationTime field value
func (o *IncomingWire) GetCreationTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetCreationTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreationTime, true
}

// SetCreationTime sets field value
func (o *IncomingWire) SetCreationTime(v time.Time) {
	o.CreationTime = v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *IncomingWire) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *IncomingWire) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *IncomingWire) SetCurrency(v string) {
	o.Currency = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *IncomingWire) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *IncomingWire) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *IncomingWire) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetDeclineReason returns the DeclineReason field value if set, zero value otherwise.
func (o *IncomingWire) GetDeclineReason() string {
	if o == nil || IsNil(o.DeclineReason) {
		var ret string
		return ret
	}
	return *o.DeclineReason
}

// GetDeclineReasonOk returns a tuple with the DeclineReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetDeclineReasonOk() (*string, bool) {
	if o == nil || IsNil(o.DeclineReason) {
		return nil, false
	}
	return o.DeclineReason, true
}

// HasDeclineReason returns a boolean if a field has been set.
func (o *IncomingWire) HasDeclineReason() bool {
	if o != nil && !IsNil(o.DeclineReason) {
		return true
	}

	return false
}

// SetDeclineReason gets a reference to the given string and assigns it to the DeclineReason field.
func (o *IncomingWire) SetDeclineReason(v string) {
	o.DeclineReason = &v
}

// GetEffectiveDate returns the EffectiveDate field value if set, zero value otherwise.
func (o *IncomingWire) GetEffectiveDate() string {
	if o == nil || IsNil(o.EffectiveDate) {
		var ret string
		return ret
	}
	return *o.EffectiveDate
}

// GetEffectiveDateOk returns a tuple with the EffectiveDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetEffectiveDateOk() (*string, bool) {
	if o == nil || IsNil(o.EffectiveDate) {
		return nil, false
	}
	return o.EffectiveDate, true
}

// HasEffectiveDate returns a boolean if a field has been set.
func (o *IncomingWire) HasEffectiveDate() bool {
	if o != nil && !IsNil(o.EffectiveDate) {
		return true
	}

	return false
}

// SetEffectiveDate gets a reference to the given string and assigns it to the EffectiveDate field.
func (o *IncomingWire) SetEffectiveDate(v string) {
	o.EffectiveDate = &v
}

// GetEndToEndIdentification returns the EndToEndIdentification field value if set, zero value otherwise.
func (o *IncomingWire) GetEndToEndIdentification() string {
	if o == nil || IsNil(o.EndToEndIdentification) {
		var ret string
		return ret
	}
	return *o.EndToEndIdentification
}

// GetEndToEndIdentificationOk returns a tuple with the EndToEndIdentification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetEndToEndIdentificationOk() (*string, bool) {
	if o == nil || IsNil(o.EndToEndIdentification) {
		return nil, false
	}
	return o.EndToEndIdentification, true
}

// HasEndToEndIdentification returns a boolean if a field has been set.
func (o *IncomingWire) HasEndToEndIdentification() bool {
	if o != nil && !IsNil(o.EndToEndIdentification) {
		return true
	}

	return false
}

// SetEndToEndIdentification gets a reference to the given string and assigns it to the EndToEndIdentification field.
func (o *IncomingWire) SetEndToEndIdentification(v string) {
	o.EndToEndIdentification = &v
}

// GetId returns the Id field value
func (o *IncomingWire) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IncomingWire) SetId(v string) {
	o.Id = v
}

// GetInputMessageAccountabilityData returns the InputMessageAccountabilityData field value if set, zero value otherwise.
func (o *IncomingWire) GetInputMessageAccountabilityData() string {
	if o == nil || IsNil(o.InputMessageAccountabilityData) {
		var ret string
		return ret
	}
	return *o.InputMessageAccountabilityData
}

// GetInputMessageAccountabilityDataOk returns a tuple with the InputMessageAccountabilityData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetInputMessageAccountabilityDataOk() (*string, bool) {
	if o == nil || IsNil(o.InputMessageAccountabilityData) {
		return nil, false
	}
	return o.InputMessageAccountabilityData, true
}

// HasInputMessageAccountabilityData returns a boolean if a field has been set.
func (o *IncomingWire) HasInputMessageAccountabilityData() bool {
	if o != nil && !IsNil(o.InputMessageAccountabilityData) {
		return true
	}

	return false
}

// SetInputMessageAccountabilityData gets a reference to the given string and assigns it to the InputMessageAccountabilityData field.
func (o *IncomingWire) SetInputMessageAccountabilityData(v string) {
	o.InputMessageAccountabilityData = &v
}

// GetInstructionIdentification returns the InstructionIdentification field value if set, zero value otherwise.
func (o *IncomingWire) GetInstructionIdentification() string {
	if o == nil || IsNil(o.InstructionIdentification) {
		var ret string
		return ret
	}
	return *o.InstructionIdentification
}

// GetInstructionIdentificationOk returns a tuple with the InstructionIdentification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetInstructionIdentificationOk() (*string, bool) {
	if o == nil || IsNil(o.InstructionIdentification) {
		return nil, false
	}
	return o.InstructionIdentification, true
}

// HasInstructionIdentification returns a boolean if a field has been set.
func (o *IncomingWire) HasInstructionIdentification() bool {
	if o != nil && !IsNil(o.InstructionIdentification) {
		return true
	}

	return false
}

// SetInstructionIdentification gets a reference to the given string and assigns it to the InstructionIdentification field.
func (o *IncomingWire) SetInstructionIdentification(v string) {
	o.InstructionIdentification = &v
}

// GetIsReturn returns the IsReturn field value
func (o *IncomingWire) GetIsReturn() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsReturn
}

// GetIsReturnOk returns a tuple with the IsReturn field value
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetIsReturnOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsReturn, true
}

// SetIsReturn sets field value
func (o *IncomingWire) SetIsReturn(v bool) {
	o.IsReturn = v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *IncomingWire) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *IncomingWire) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *IncomingWire) SetNetwork(v string) {
	o.Network = &v
}

// GetOriginatingAccountNumber returns the OriginatingAccountNumber field value if set, zero value otherwise.
func (o *IncomingWire) GetOriginatingAccountNumber() string {
	if o == nil || IsNil(o.OriginatingAccountNumber) {
		var ret string
		return ret
	}
	return *o.OriginatingAccountNumber
}

// GetOriginatingAccountNumberOk returns a tuple with the OriginatingAccountNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetOriginatingAccountNumberOk() (*string, bool) {
	if o == nil || IsNil(o.OriginatingAccountNumber) {
		return nil, false
	}
	return o.OriginatingAccountNumber, true
}

// HasOriginatingAccountNumber returns a boolean if a field has been set.
func (o *IncomingWire) HasOriginatingAccountNumber() bool {
	if o != nil && !IsNil(o.OriginatingAccountNumber) {
		return true
	}

	return false
}

// SetOriginatingAccountNumber gets a reference to the given string and assigns it to the OriginatingAccountNumber field.
func (o *IncomingWire) SetOriginatingAccountNumber(v string) {
	o.OriginatingAccountNumber = &v
}

// GetReceiver returns the Receiver field value
func (o *IncomingWire) GetReceiver() Party {
	if o == nil {
		var ret Party
		return ret
	}

	return o.Receiver
}

// GetReceiverOk returns a tuple with the Receiver field value
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetReceiverOk() (*Party, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Receiver, true
}

// SetReceiver sets field value
func (o *IncomingWire) SetReceiver(v Party) {
	o.Receiver = v
}

// GetReceivingAccountId returns the ReceivingAccountId field value if set, zero value otherwise.
func (o *IncomingWire) GetReceivingAccountId() string {
	if o == nil || IsNil(o.ReceivingAccountId) {
		var ret string
		return ret
	}
	return *o.ReceivingAccountId
}

// GetReceivingAccountIdOk returns a tuple with the ReceivingAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetReceivingAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReceivingAccountId) {
		return nil, false
	}
	return o.ReceivingAccountId, true
}

// HasReceivingAccountId returns a boolean if a field has been set.
func (o *IncomingWire) HasReceivingAccountId() bool {
	if o != nil && !IsNil(o.ReceivingAccountId) {
		return true
	}

	return false
}

// SetReceivingAccountId gets a reference to the given string and assigns it to the ReceivingAccountId field.
func (o *IncomingWire) SetReceivingAccountId(v string) {
	o.ReceivingAccountId = &v
}

// GetReceivingAccountNumber returns the ReceivingAccountNumber field value
func (o *IncomingWire) GetReceivingAccountNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReceivingAccountNumber
}

// GetReceivingAccountNumberOk returns a tuple with the ReceivingAccountNumber field value
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetReceivingAccountNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceivingAccountNumber, true
}

// SetReceivingAccountNumber sets field value
func (o *IncomingWire) SetReceivingAccountNumber(v string) {
	o.ReceivingAccountNumber = v
}

// GetRecipientMessage returns the RecipientMessage field value if set, zero value otherwise.
func (o *IncomingWire) GetRecipientMessage() string {
	if o == nil || IsNil(o.RecipientMessage) {
		var ret string
		return ret
	}
	return *o.RecipientMessage
}

// GetRecipientMessageOk returns a tuple with the RecipientMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetRecipientMessageOk() (*string, bool) {
	if o == nil || IsNil(o.RecipientMessage) {
		return nil, false
	}
	return o.RecipientMessage, true
}

// HasRecipientMessage returns a boolean if a field has been set.
func (o *IncomingWire) HasRecipientMessage() bool {
	if o != nil && !IsNil(o.RecipientMessage) {
		return true
	}

	return false
}

// SetRecipientMessage gets a reference to the given string and assigns it to the RecipientMessage field.
func (o *IncomingWire) SetRecipientMessage(v string) {
	o.RecipientMessage = &v
}

// GetReturnData returns the ReturnData field value if set, zero value otherwise.
func (o *IncomingWire) GetReturnData() ReturnData {
	if o == nil || IsNil(o.ReturnData) {
		var ret ReturnData
		return ret
	}
	return *o.ReturnData
}

// GetReturnDataOk returns a tuple with the ReturnData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetReturnDataOk() (*ReturnData, bool) {
	if o == nil || IsNil(o.ReturnData) {
		return nil, false
	}
	return o.ReturnData, true
}

// HasReturnData returns a boolean if a field has been set.
func (o *IncomingWire) HasReturnData() bool {
	if o != nil && !IsNil(o.ReturnData) {
		return true
	}

	return false
}

// SetReturnData gets a reference to the given ReturnData and assigns it to the ReturnData field.
func (o *IncomingWire) SetReturnData(v ReturnData) {
	o.ReturnData = &v
}

// GetReturnReason returns the ReturnReason field value if set, zero value otherwise.
func (o *IncomingWire) GetReturnReason() string {
	if o == nil || IsNil(o.ReturnReason) {
		var ret string
		return ret
	}
	return *o.ReturnReason
}

// GetReturnReasonOk returns a tuple with the ReturnReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetReturnReasonOk() (*string, bool) {
	if o == nil || IsNil(o.ReturnReason) {
		return nil, false
	}
	return o.ReturnReason, true
}

// HasReturnReason returns a boolean if a field has been set.
func (o *IncomingWire) HasReturnReason() bool {
	if o != nil && !IsNil(o.ReturnReason) {
		return true
	}

	return false
}

// SetReturnReason gets a reference to the given string and assigns it to the ReturnReason field.
func (o *IncomingWire) SetReturnReason(v string) {
	o.ReturnReason = &v
}

// GetSender returns the Sender field value
func (o *IncomingWire) GetSender() Party {
	if o == nil {
		var ret Party
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetSenderOk() (*Party, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *IncomingWire) SetSender(v Party) {
	o.Sender = v
}

// GetSenderReferenceId returns the SenderReferenceId field value
func (o *IncomingWire) GetSenderReferenceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SenderReferenceId
}

// GetSenderReferenceIdOk returns a tuple with the SenderReferenceId field value
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetSenderReferenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SenderReferenceId, true
}

// SetSenderReferenceId sets field value
func (o *IncomingWire) SetSenderReferenceId(v string) {
	o.SenderReferenceId = v
}

// GetSettlementDate returns the SettlementDate field value if set, zero value otherwise.
func (o *IncomingWire) GetSettlementDate() string {
	if o == nil || IsNil(o.SettlementDate) {
		var ret string
		return ret
	}
	return *o.SettlementDate
}

// GetSettlementDateOk returns a tuple with the SettlementDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetSettlementDateOk() (*string, bool) {
	if o == nil || IsNil(o.SettlementDate) {
		return nil, false
	}
	return o.SettlementDate, true
}

// HasSettlementDate returns a boolean if a field has been set.
func (o *IncomingWire) HasSettlementDate() bool {
	if o != nil && !IsNil(o.SettlementDate) {
		return true
	}

	return false
}

// SetSettlementDate gets a reference to the given string and assigns it to the SettlementDate field.
func (o *IncomingWire) SetSettlementDate(v string) {
	o.SettlementDate = &v
}

// GetStatus returns the Status field value
func (o *IncomingWire) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *IncomingWire) SetStatus(v string) {
	o.Status = v
}

// GetTenant returns the Tenant field value
func (o *IncomingWire) GetTenant() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetTenantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tenant, true
}

// SetTenant sets field value
func (o *IncomingWire) SetTenant(v string) {
	o.Tenant = v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *IncomingWire) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *IncomingWire) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *IncomingWire) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetTransactionIdentification returns the TransactionIdentification field value if set, zero value otherwise.
func (o *IncomingWire) GetTransactionIdentification() string {
	if o == nil || IsNil(o.TransactionIdentification) {
		var ret string
		return ret
	}
	return *o.TransactionIdentification
}

// GetTransactionIdentificationOk returns a tuple with the TransactionIdentification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetTransactionIdentificationOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionIdentification) {
		return nil, false
	}
	return o.TransactionIdentification, true
}

// HasTransactionIdentification returns a boolean if a field has been set.
func (o *IncomingWire) HasTransactionIdentification() bool {
	if o != nil && !IsNil(o.TransactionIdentification) {
		return true
	}

	return false
}

// SetTransactionIdentification gets a reference to the given string and assigns it to the TransactionIdentification field.
func (o *IncomingWire) SetTransactionIdentification(v string) {
	o.TransactionIdentification = &v
}

// GetTypeSubtype returns the TypeSubtype field value if set, zero value otherwise.
func (o *IncomingWire) GetTypeSubtype() string {
	if o == nil || IsNil(o.TypeSubtype) {
		var ret string
		return ret
	}
	return *o.TypeSubtype
}

// GetTypeSubtypeOk returns a tuple with the TypeSubtype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetTypeSubtypeOk() (*string, bool) {
	if o == nil || IsNil(o.TypeSubtype) {
		return nil, false
	}
	return o.TypeSubtype, true
}

// HasTypeSubtype returns a boolean if a field has been set.
func (o *IncomingWire) HasTypeSubtype() bool {
	if o != nil && !IsNil(o.TypeSubtype) {
		return true
	}

	return false
}

// SetTypeSubtype gets a reference to the given string and assigns it to the TypeSubtype field.
func (o *IncomingWire) SetTypeSubtype(v string) {
	o.TypeSubtype = &v
}

// GetUetr returns the Uetr field value if set, zero value otherwise.
func (o *IncomingWire) GetUetr() string {
	if o == nil || IsNil(o.Uetr) {
		var ret string
		return ret
	}
	return *o.Uetr
}

// GetUetrOk returns a tuple with the Uetr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomingWire) GetUetrOk() (*string, bool) {
	if o == nil || IsNil(o.Uetr) {
		return nil, false
	}
	return o.Uetr, true
}

// HasUetr returns a boolean if a field has been set.
func (o *IncomingWire) HasUetr() bool {
	if o != nil && !IsNil(o.Uetr) {
		return true
	}

	return false
}

// SetUetr gets a reference to the given string and assigns it to the Uetr field.
func (o *IncomingWire) SetUetr(v string) {
	o.Uetr = &v
}

func (o IncomingWire) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IncomingWire) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	if !IsNil(o.BankMessage) {
		toSerialize["bank_message"] = o.BankMessage
	}
	toSerialize["creation_time"] = o.CreationTime
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customer_id"] = o.CustomerId
	}
	if !IsNil(o.DeclineReason) {
		toSerialize["decline_reason"] = o.DeclineReason
	}
	if !IsNil(o.EffectiveDate) {
		toSerialize["effective_date"] = o.EffectiveDate
	}
	if !IsNil(o.EndToEndIdentification) {
		toSerialize["end_to_end_identification"] = o.EndToEndIdentification
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.InputMessageAccountabilityData) {
		toSerialize["input_message_accountability_data"] = o.InputMessageAccountabilityData
	}
	if !IsNil(o.InstructionIdentification) {
		toSerialize["instruction_identification"] = o.InstructionIdentification
	}
	toSerialize["is_return"] = o.IsReturn
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.OriginatingAccountNumber) {
		toSerialize["originating_account_number"] = o.OriginatingAccountNumber
	}
	toSerialize["receiver"] = o.Receiver
	if !IsNil(o.ReceivingAccountId) {
		toSerialize["receiving_account_id"] = o.ReceivingAccountId
	}
	toSerialize["receiving_account_number"] = o.ReceivingAccountNumber
	if !IsNil(o.RecipientMessage) {
		toSerialize["recipient_message"] = o.RecipientMessage
	}
	if !IsNil(o.ReturnData) {
		toSerialize["return_data"] = o.ReturnData
	}
	if !IsNil(o.ReturnReason) {
		toSerialize["return_reason"] = o.ReturnReason
	}
	toSerialize["sender"] = o.Sender
	toSerialize["sender_reference_id"] = o.SenderReferenceId
	if !IsNil(o.SettlementDate) {
		toSerialize["settlement_date"] = o.SettlementDate
	}
	toSerialize["status"] = o.Status
	toSerialize["tenant"] = o.Tenant
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	if !IsNil(o.TransactionIdentification) {
		toSerialize["transaction_identification"] = o.TransactionIdentification
	}
	if !IsNil(o.TypeSubtype) {
		toSerialize["type_subtype"] = o.TypeSubtype
	}
	if !IsNil(o.Uetr) {
		toSerialize["uetr"] = o.Uetr
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IncomingWire) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"creation_time",
		"id",
		"is_return",
		"receiver",
		"receiving_account_number",
		"sender",
		"sender_reference_id",
		"status",
		"tenant",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIncomingWire := _IncomingWire{}

	err = json.Unmarshal(data, &varIncomingWire)

	if err != nil {
		return err
	}

	*o = IncomingWire(varIncomingWire)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "amount")
		delete(additionalProperties, "bank_message")
		delete(additionalProperties, "creation_time")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "customer_id")
		delete(additionalProperties, "decline_reason")
		delete(additionalProperties, "effective_date")
		delete(additionalProperties, "end_to_end_identification")
		delete(additionalProperties, "id")
		delete(additionalProperties, "input_message_accountability_data")
		delete(additionalProperties, "instruction_identification")
		delete(additionalProperties, "is_return")
		delete(additionalProperties, "network")
		delete(additionalProperties, "originating_account_number")
		delete(additionalProperties, "receiver")
		delete(additionalProperties, "receiving_account_id")
		delete(additionalProperties, "receiving_account_number")
		delete(additionalProperties, "recipient_message")
		delete(additionalProperties, "return_data")
		delete(additionalProperties, "return_reason")
		delete(additionalProperties, "sender")
		delete(additionalProperties, "sender_reference_id")
		delete(additionalProperties, "settlement_date")
		delete(additionalProperties, "status")
		delete(additionalProperties, "tenant")
		delete(additionalProperties, "transaction_id")
		delete(additionalProperties, "transaction_identification")
		delete(additionalProperties, "type_subtype")
		delete(additionalProperties, "uetr")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIncomingWire struct {
	value *IncomingWire
	isSet bool
}

func (v NullableIncomingWire) Get() *IncomingWire {
	return v.value
}

func (v *NullableIncomingWire) Set(val *IncomingWire) {
	v.value = val
	v.isSet = true
}

func (v NullableIncomingWire) IsSet() bool {
	return v.isSet
}

func (v *NullableIncomingWire) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncomingWire(val *IncomingWire) *NullableIncomingWire {
	return &NullableIncomingWire{value: val, isSet: true}
}

func (v NullableIncomingWire) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncomingWire) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
