/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the RestrictedApplicationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestrictedApplicationResponse{}

// RestrictedApplicationResponse struct for RestrictedApplicationResponse
type RestrictedApplicationResponse struct {
	ApplicationDetails RestrictedApplicationDetails `json:"application_details"`
	// Business ID for the application. An application must have either a Business or a customer associated with it.
	BusinessId *string `json:"business_id,omitempty"`
	// Customer ID for the application. An application must have either a Business or a customer associated with it.
	CustomerId *string `json:"customer_id,omitempty"`
	// A description of the restricted account application
	Description *string                     `json:"description,omitempty"`
	Status      RestrictedApplicationStatus `json:"status"`
	Type        ApplicationType             `json:"type"`
	// Application creation timestamp in RFC3339 format
	CreationTime time.Time `json:"creation_time"`
	// Generated ID for the application
	Id string `json:"id"`
	// Timestamp of the last application modification in RFC3339 format
	LastUpdatedTime      time.Time `json:"last_updated_time"`
	AdditionalProperties map[string]interface{}
}

type _RestrictedApplicationResponse RestrictedApplicationResponse

// NewRestrictedApplicationResponse instantiates a new RestrictedApplicationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestrictedApplicationResponse(applicationDetails RestrictedApplicationDetails, status RestrictedApplicationStatus, type_ ApplicationType, creationTime time.Time, id string, lastUpdatedTime time.Time) *RestrictedApplicationResponse {
	this := RestrictedApplicationResponse{}
	this.ApplicationDetails = applicationDetails
	this.Status = status
	this.Type = type_
	this.CreationTime = creationTime
	this.Id = id
	this.LastUpdatedTime = lastUpdatedTime
	return &this
}

// NewRestrictedApplicationResponseWithDefaults instantiates a new RestrictedApplicationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestrictedApplicationResponseWithDefaults() *RestrictedApplicationResponse {
	this := RestrictedApplicationResponse{}
	return &this
}

// GetApplicationDetails returns the ApplicationDetails field value
func (o *RestrictedApplicationResponse) GetApplicationDetails() RestrictedApplicationDetails {
	if o == nil {
		var ret RestrictedApplicationDetails
		return ret
	}

	return o.ApplicationDetails
}

// GetApplicationDetailsOk returns a tuple with the ApplicationDetails field value
// and a boolean to check if the value has been set.
func (o *RestrictedApplicationResponse) GetApplicationDetailsOk() (*RestrictedApplicationDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationDetails, true
}

// SetApplicationDetails sets field value
func (o *RestrictedApplicationResponse) SetApplicationDetails(v RestrictedApplicationDetails) {
	o.ApplicationDetails = v
}

// GetBusinessId returns the BusinessId field value if set, zero value otherwise.
func (o *RestrictedApplicationResponse) GetBusinessId() string {
	if o == nil || IsNil(o.BusinessId) {
		var ret string
		return ret
	}
	return *o.BusinessId
}

// GetBusinessIdOk returns a tuple with the BusinessId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestrictedApplicationResponse) GetBusinessIdOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessId) {
		return nil, false
	}
	return o.BusinessId, true
}

// HasBusinessId returns a boolean if a field has been set.
func (o *RestrictedApplicationResponse) HasBusinessId() bool {
	if o != nil && !IsNil(o.BusinessId) {
		return true
	}

	return false
}

// SetBusinessId gets a reference to the given string and assigns it to the BusinessId field.
func (o *RestrictedApplicationResponse) SetBusinessId(v string) {
	o.BusinessId = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *RestrictedApplicationResponse) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestrictedApplicationResponse) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *RestrictedApplicationResponse) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *RestrictedApplicationResponse) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RestrictedApplicationResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestrictedApplicationResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RestrictedApplicationResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RestrictedApplicationResponse) SetDescription(v string) {
	o.Description = &v
}

// GetStatus returns the Status field value
func (o *RestrictedApplicationResponse) GetStatus() RestrictedApplicationStatus {
	if o == nil {
		var ret RestrictedApplicationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RestrictedApplicationResponse) GetStatusOk() (*RestrictedApplicationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RestrictedApplicationResponse) SetStatus(v RestrictedApplicationStatus) {
	o.Status = v
}

// GetType returns the Type field value
func (o *RestrictedApplicationResponse) GetType() ApplicationType {
	if o == nil {
		var ret ApplicationType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RestrictedApplicationResponse) GetTypeOk() (*ApplicationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RestrictedApplicationResponse) SetType(v ApplicationType) {
	o.Type = v
}

// GetCreationTime returns the CreationTime field value
func (o *RestrictedApplicationResponse) GetCreationTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value
// and a boolean to check if the value has been set.
func (o *RestrictedApplicationResponse) GetCreationTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreationTime, true
}

// SetCreationTime sets field value
func (o *RestrictedApplicationResponse) SetCreationTime(v time.Time) {
	o.CreationTime = v
}

// GetId returns the Id field value
func (o *RestrictedApplicationResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RestrictedApplicationResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RestrictedApplicationResponse) SetId(v string) {
	o.Id = v
}

// GetLastUpdatedTime returns the LastUpdatedTime field value
func (o *RestrictedApplicationResponse) GetLastUpdatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUpdatedTime
}

// GetLastUpdatedTimeOk returns a tuple with the LastUpdatedTime field value
// and a boolean to check if the value has been set.
func (o *RestrictedApplicationResponse) GetLastUpdatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdatedTime, true
}

// SetLastUpdatedTime sets field value
func (o *RestrictedApplicationResponse) SetLastUpdatedTime(v time.Time) {
	o.LastUpdatedTime = v
}

func (o RestrictedApplicationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestrictedApplicationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["application_details"] = o.ApplicationDetails
	if !IsNil(o.BusinessId) {
		toSerialize["business_id"] = o.BusinessId
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customer_id"] = o.CustomerId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["status"] = o.Status
	toSerialize["type"] = o.Type
	toSerialize["creation_time"] = o.CreationTime
	toSerialize["id"] = o.Id
	toSerialize["last_updated_time"] = o.LastUpdatedTime

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RestrictedApplicationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"application_details",
		"status",
		"type",
		"creation_time",
		"id",
		"last_updated_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRestrictedApplicationResponse := _RestrictedApplicationResponse{}

	err = json.Unmarshal(data, &varRestrictedApplicationResponse)

	if err != nil {
		return err
	}

	*o = RestrictedApplicationResponse(varRestrictedApplicationResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "application_details")
		delete(additionalProperties, "business_id")
		delete(additionalProperties, "customer_id")
		delete(additionalProperties, "description")
		delete(additionalProperties, "status")
		delete(additionalProperties, "type")
		delete(additionalProperties, "creation_time")
		delete(additionalProperties, "id")
		delete(additionalProperties, "last_updated_time")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRestrictedApplicationResponse struct {
	value *RestrictedApplicationResponse
	isSet bool
}

func (v NullableRestrictedApplicationResponse) Get() *RestrictedApplicationResponse {
	return v.value
}

func (v *NullableRestrictedApplicationResponse) Set(val *RestrictedApplicationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRestrictedApplicationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRestrictedApplicationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestrictedApplicationResponse(val *RestrictedApplicationResponse) *NullableRestrictedApplicationResponse {
	return &NullableRestrictedApplicationResponse{value: val, isSet: true}
}

func (v NullableRestrictedApplicationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestrictedApplicationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
