/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
)

// CardResponse - struct for CardResponse
type CardResponse struct {
	CreditCardResponse *CreditCardResponse
	DebitCardResponse  *DebitCardResponse
}

// CreditCardResponseAsCardResponse is a convenience function that returns CreditCardResponse wrapped in CardResponse
func CreditCardResponseAsCardResponse(v *CreditCardResponse) CardResponse {
	return CardResponse{
		CreditCardResponse: v,
	}
}

// DebitCardResponseAsCardResponse is a convenience function that returns DebitCardResponse wrapped in CardResponse
func DebitCardResponseAsCardResponse(v *DebitCardResponse) CardResponse {
	return CardResponse{
		DebitCardResponse: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *CardResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'CREDIT'
	if jsonDict["type"] == "CREDIT" {
		// try to unmarshal JSON data into CreditCardResponse
		err = json.Unmarshal(data, &dst.CreditCardResponse)
		if err == nil {
			return nil // data stored in dst.CreditCardResponse, return on the first match
		} else {
			dst.CreditCardResponse = nil
			return fmt.Errorf("failed to unmarshal CardResponse as CreditCardResponse: %s", err.Error())
		}
	}

	// check if the discriminator value is 'DEBIT'
	if jsonDict["type"] == "DEBIT" {
		// try to unmarshal JSON data into DebitCardResponse
		err = json.Unmarshal(data, &dst.DebitCardResponse)
		if err == nil {
			return nil // data stored in dst.DebitCardResponse, return on the first match
		} else {
			dst.DebitCardResponse = nil
			return fmt.Errorf("failed to unmarshal CardResponse as DebitCardResponse: %s", err.Error())
		}
	}

	// check if the discriminator value is 'PREPAID'
	if jsonDict["type"] == "PREPAID" {
		// try to unmarshal JSON data into DebitCardResponse
		err = json.Unmarshal(data, &dst.DebitCardResponse)
		if err == nil {
			return nil // data stored in dst.DebitCardResponse, return on the first match
		} else {
			dst.DebitCardResponse = nil
			return fmt.Errorf("failed to unmarshal CardResponse as DebitCardResponse: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CardResponse) MarshalJSON() ([]byte, error) {
	if src.CreditCardResponse != nil {
		return json.Marshal(&src.CreditCardResponse)
	}

	if src.DebitCardResponse != nil {
		return json.Marshal(&src.DebitCardResponse)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CardResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CreditCardResponse != nil {
		return obj.CreditCardResponse
	}

	if obj.DebitCardResponse != nil {
		return obj.DebitCardResponse
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CardResponse) GetActualInstanceValue() interface{} {
	if obj.CreditCardResponse != nil {
		return *obj.CreditCardResponse
	}

	if obj.DebitCardResponse != nil {
		return *obj.DebitCardResponse
	}

	// all schemas are nil
	return nil
}

type NullableCardResponse struct {
	value *CardResponse
	isSet bool
}

func (v NullableCardResponse) Get() *CardResponse {
	return v.value
}

func (v *NullableCardResponse) Set(val *CardResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCardResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCardResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardResponse(val *CardResponse) *NullableCardResponse {
	return &NullableCardResponse{value: val, isSet: true}
}

func (v NullableCardResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
