/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the TransferResponseToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferResponseToken{}

// TransferResponseToken struct for TransferResponseToken
type TransferResponseToken struct {
	// The ID of the Synctera account into which or from which funds were moved
	AccountId string `json:"account_id"`
	// Amount of the transfer in cents
	Amount       int32     `json:"amount"`
	CreationTime time.Time `json:"creation_time"`
	// ISO 4217  Alpha-3 currency code
	Currency string `json:"currency"`
	// The customer_id of the cardholder
	CustomerId string `json:"customer_id"`
	// The ID of the transfer
	Id              string    `json:"id"`
	LastUpdatedTime time.Time `json:"last_updated_time"`
	Merchant        Merchant  `json:"merchant"`
	// If available, a human readable string indicating why a transfer was declined downstream of our system
	NetworkDeclineDetails *string `json:"network_decline_details,omitempty"`
	// The reason for the status, e.g. INSUFFICIENT_FUNDS, SUSPECTED_FRAUD, NETWORK_DECLINED
	Reason *string        `json:"reason,omitempty"`
	Status TransferStatus `json:"status"`
	// The id of the tenant containing the resource.
	Tenant string `json:"tenant"`
	// The transaction ID
	TransactionId        *string             `json:"transaction_id,omitempty"`
	CardDetails          ExternalCardDetails `json:"card_details"`
	Type                 TransferType        `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _TransferResponseToken TransferResponseToken

// NewTransferResponseToken instantiates a new TransferResponseToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferResponseToken(accountId string, amount int32, creationTime time.Time, currency string, customerId string, id string, lastUpdatedTime time.Time, merchant Merchant, status TransferStatus, tenant string, cardDetails ExternalCardDetails, type_ TransferType) *TransferResponseToken {
	this := TransferResponseToken{}
	this.AccountId = accountId
	this.Amount = amount
	this.CreationTime = creationTime
	this.Currency = currency
	this.CustomerId = customerId
	this.Id = id
	this.LastUpdatedTime = lastUpdatedTime
	this.Merchant = merchant
	this.Status = status
	this.Tenant = tenant
	this.CardDetails = cardDetails
	this.Type = type_
	return &this
}

// NewTransferResponseTokenWithDefaults instantiates a new TransferResponseToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferResponseTokenWithDefaults() *TransferResponseToken {
	this := TransferResponseToken{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *TransferResponseToken) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *TransferResponseToken) SetAccountId(v string) {
	o.AccountId = v
}

// GetAmount returns the Amount field value
func (o *TransferResponseToken) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TransferResponseToken) SetAmount(v int32) {
	o.Amount = v
}

// GetCreationTime returns the CreationTime field value
func (o *TransferResponseToken) GetCreationTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetCreationTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreationTime, true
}

// SetCreationTime sets field value
func (o *TransferResponseToken) SetCreationTime(v time.Time) {
	o.CreationTime = v
}

// GetCurrency returns the Currency field value
func (o *TransferResponseToken) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *TransferResponseToken) SetCurrency(v string) {
	o.Currency = v
}

// GetCustomerId returns the CustomerId field value
func (o *TransferResponseToken) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *TransferResponseToken) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetId returns the Id field value
func (o *TransferResponseToken) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TransferResponseToken) SetId(v string) {
	o.Id = v
}

// GetLastUpdatedTime returns the LastUpdatedTime field value
func (o *TransferResponseToken) GetLastUpdatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUpdatedTime
}

// GetLastUpdatedTimeOk returns a tuple with the LastUpdatedTime field value
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetLastUpdatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdatedTime, true
}

// SetLastUpdatedTime sets field value
func (o *TransferResponseToken) SetLastUpdatedTime(v time.Time) {
	o.LastUpdatedTime = v
}

// GetMerchant returns the Merchant field value
func (o *TransferResponseToken) GetMerchant() Merchant {
	if o == nil {
		var ret Merchant
		return ret
	}

	return o.Merchant
}

// GetMerchantOk returns a tuple with the Merchant field value
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetMerchantOk() (*Merchant, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Merchant, true
}

// SetMerchant sets field value
func (o *TransferResponseToken) SetMerchant(v Merchant) {
	o.Merchant = v
}

// GetNetworkDeclineDetails returns the NetworkDeclineDetails field value if set, zero value otherwise.
func (o *TransferResponseToken) GetNetworkDeclineDetails() string {
	if o == nil || IsNil(o.NetworkDeclineDetails) {
		var ret string
		return ret
	}
	return *o.NetworkDeclineDetails
}

// GetNetworkDeclineDetailsOk returns a tuple with the NetworkDeclineDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetNetworkDeclineDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkDeclineDetails) {
		return nil, false
	}
	return o.NetworkDeclineDetails, true
}

// HasNetworkDeclineDetails returns a boolean if a field has been set.
func (o *TransferResponseToken) HasNetworkDeclineDetails() bool {
	if o != nil && !IsNil(o.NetworkDeclineDetails) {
		return true
	}

	return false
}

// SetNetworkDeclineDetails gets a reference to the given string and assigns it to the NetworkDeclineDetails field.
func (o *TransferResponseToken) SetNetworkDeclineDetails(v string) {
	o.NetworkDeclineDetails = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *TransferResponseToken) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *TransferResponseToken) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *TransferResponseToken) SetReason(v string) {
	o.Reason = &v
}

// GetStatus returns the Status field value
func (o *TransferResponseToken) GetStatus() TransferStatus {
	if o == nil {
		var ret TransferStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetStatusOk() (*TransferStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TransferResponseToken) SetStatus(v TransferStatus) {
	o.Status = v
}

// GetTenant returns the Tenant field value
func (o *TransferResponseToken) GetTenant() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetTenantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tenant, true
}

// SetTenant sets field value
func (o *TransferResponseToken) SetTenant(v string) {
	o.Tenant = v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *TransferResponseToken) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *TransferResponseToken) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *TransferResponseToken) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetCardDetails returns the CardDetails field value
func (o *TransferResponseToken) GetCardDetails() ExternalCardDetails {
	if o == nil {
		var ret ExternalCardDetails
		return ret
	}

	return o.CardDetails
}

// GetCardDetailsOk returns a tuple with the CardDetails field value
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetCardDetailsOk() (*ExternalCardDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardDetails, true
}

// SetCardDetails sets field value
func (o *TransferResponseToken) SetCardDetails(v ExternalCardDetails) {
	o.CardDetails = v
}

// GetType returns the Type field value
func (o *TransferResponseToken) GetType() TransferType {
	if o == nil {
		var ret TransferType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TransferResponseToken) GetTypeOk() (*TransferType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TransferResponseToken) SetType(v TransferType) {
	o.Type = v
}

func (o TransferResponseToken) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferResponseToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["amount"] = o.Amount
	toSerialize["creation_time"] = o.CreationTime
	toSerialize["currency"] = o.Currency
	toSerialize["customer_id"] = o.CustomerId
	toSerialize["id"] = o.Id
	toSerialize["last_updated_time"] = o.LastUpdatedTime
	toSerialize["merchant"] = o.Merchant
	if !IsNil(o.NetworkDeclineDetails) {
		toSerialize["network_decline_details"] = o.NetworkDeclineDetails
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	toSerialize["status"] = o.Status
	toSerialize["tenant"] = o.Tenant
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	toSerialize["card_details"] = o.CardDetails
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TransferResponseToken) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"amount",
		"creation_time",
		"currency",
		"customer_id",
		"id",
		"last_updated_time",
		"merchant",
		"status",
		"tenant",
		"card_details",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransferResponseToken := _TransferResponseToken{}

	err = json.Unmarshal(data, &varTransferResponseToken)

	if err != nil {
		return err
	}

	*o = TransferResponseToken(varTransferResponseToken)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "creation_time")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "customer_id")
		delete(additionalProperties, "id")
		delete(additionalProperties, "last_updated_time")
		delete(additionalProperties, "merchant")
		delete(additionalProperties, "network_decline_details")
		delete(additionalProperties, "reason")
		delete(additionalProperties, "status")
		delete(additionalProperties, "tenant")
		delete(additionalProperties, "transaction_id")
		delete(additionalProperties, "card_details")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTransferResponseToken struct {
	value *TransferResponseToken
	isSet bool
}

func (v NullableTransferResponseToken) Get() *TransferResponseToken {
	return v.value
}

func (v *NullableTransferResponseToken) Set(val *TransferResponseToken) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferResponseToken) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferResponseToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferResponseToken(val *TransferResponseToken) *NullableTransferResponseToken {
	return &NullableTransferResponseToken{value: val, isSet: true}
}

func (v NullableTransferResponseToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferResponseToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
