/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
)

// checks if the FeeTemplatePatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeeTemplatePatch{}

// FeeTemplatePatch struct for FeeTemplatePatch
type FeeTemplatePatch struct {
	// The default amount of the fee in ISO 4217 minor currency units, e.g. cents. The internal account will be debited this amount. Can be overridden when creating a fee.
	Amount *int32 `json:"amount,omitempty"`
	// currency for the fee, as a three character ISO 4217 alphabetic currency code.
	Currency *string `json:"currency,omitempty"`
	// The description of the fee template.
	Description *string `json:"description,omitempty"`
	// The ID of default internal_account to use as the destination of the fee transfer. Cannot be a system internal account.
	InternalAccountId *string `json:"internal_account_id,omitempty"`
	// Whether the fee template is enabled. If false, fees cannot be created from this template.
	IsEnabled *bool `json:"is_enabled,omitempty"`
	// Optional field to store additional information about the resource. Intended to be used by the integrator to store non-sensitive data.
	Metadata             map[string]interface{} `json:"metadata,omitempty"`
	Subtype              *FeeSubtypePost        `json:"subtype,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FeeTemplatePatch FeeTemplatePatch

// NewFeeTemplatePatch instantiates a new FeeTemplatePatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeeTemplatePatch() *FeeTemplatePatch {
	this := FeeTemplatePatch{}
	return &this
}

// NewFeeTemplatePatchWithDefaults instantiates a new FeeTemplatePatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeeTemplatePatchWithDefaults() *FeeTemplatePatch {
	this := FeeTemplatePatch{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *FeeTemplatePatch) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeeTemplatePatch) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *FeeTemplatePatch) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *FeeTemplatePatch) SetAmount(v int32) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *FeeTemplatePatch) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeeTemplatePatch) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *FeeTemplatePatch) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *FeeTemplatePatch) SetCurrency(v string) {
	o.Currency = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *FeeTemplatePatch) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeeTemplatePatch) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *FeeTemplatePatch) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *FeeTemplatePatch) SetDescription(v string) {
	o.Description = &v
}

// GetInternalAccountId returns the InternalAccountId field value if set, zero value otherwise.
func (o *FeeTemplatePatch) GetInternalAccountId() string {
	if o == nil || IsNil(o.InternalAccountId) {
		var ret string
		return ret
	}
	return *o.InternalAccountId
}

// GetInternalAccountIdOk returns a tuple with the InternalAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeeTemplatePatch) GetInternalAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.InternalAccountId) {
		return nil, false
	}
	return o.InternalAccountId, true
}

// HasInternalAccountId returns a boolean if a field has been set.
func (o *FeeTemplatePatch) HasInternalAccountId() bool {
	if o != nil && !IsNil(o.InternalAccountId) {
		return true
	}

	return false
}

// SetInternalAccountId gets a reference to the given string and assigns it to the InternalAccountId field.
func (o *FeeTemplatePatch) SetInternalAccountId(v string) {
	o.InternalAccountId = &v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *FeeTemplatePatch) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeeTemplatePatch) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *FeeTemplatePatch) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *FeeTemplatePatch) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *FeeTemplatePatch) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeeTemplatePatch) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *FeeTemplatePatch) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *FeeTemplatePatch) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetSubtype returns the Subtype field value if set, zero value otherwise.
func (o *FeeTemplatePatch) GetSubtype() FeeSubtypePost {
	if o == nil || IsNil(o.Subtype) {
		var ret FeeSubtypePost
		return ret
	}
	return *o.Subtype
}

// GetSubtypeOk returns a tuple with the Subtype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeeTemplatePatch) GetSubtypeOk() (*FeeSubtypePost, bool) {
	if o == nil || IsNil(o.Subtype) {
		return nil, false
	}
	return o.Subtype, true
}

// HasSubtype returns a boolean if a field has been set.
func (o *FeeTemplatePatch) HasSubtype() bool {
	if o != nil && !IsNil(o.Subtype) {
		return true
	}

	return false
}

// SetSubtype gets a reference to the given FeeSubtypePost and assigns it to the Subtype field.
func (o *FeeTemplatePatch) SetSubtype(v FeeSubtypePost) {
	o.Subtype = &v
}

func (o FeeTemplatePatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeeTemplatePatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.InternalAccountId) {
		toSerialize["internal_account_id"] = o.InternalAccountId
	}
	if !IsNil(o.IsEnabled) {
		toSerialize["is_enabled"] = o.IsEnabled
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Subtype) {
		toSerialize["subtype"] = o.Subtype
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FeeTemplatePatch) UnmarshalJSON(data []byte) (err error) {
	varFeeTemplatePatch := _FeeTemplatePatch{}

	err = json.Unmarshal(data, &varFeeTemplatePatch)

	if err != nil {
		return err
	}

	*o = FeeTemplatePatch(varFeeTemplatePatch)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "amount")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "description")
		delete(additionalProperties, "internal_account_id")
		delete(additionalProperties, "is_enabled")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "subtype")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFeeTemplatePatch struct {
	value *FeeTemplatePatch
	isSet bool
}

func (v NullableFeeTemplatePatch) Get() *FeeTemplatePatch {
	return v.value
}

func (v *NullableFeeTemplatePatch) Set(val *FeeTemplatePatch) {
	v.value = val
	v.isSet = true
}

func (v NullableFeeTemplatePatch) IsSet() bool {
	return v.isSet
}

func (v *NullableFeeTemplatePatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeeTemplatePatch(val *FeeTemplatePatch) *NullableFeeTemplatePatch {
	return &NullableFeeTemplatePatch{value: val, isSet: true}
}

func (v NullableFeeTemplatePatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeeTemplatePatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
