/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkShipping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkShipping{}

// BulkShipping Details about the shipping method for bulk issuance.
type BulkShipping struct {
	// The address to which the bulk order will be shipped.
	Address Address `json:"address"`
	// The name of the business which the bulk order will be shipped
	BusinessName *string `json:"business_name,omitempty"`
	// Is the shipment expedited
	// Deprecated
	IsExpeditedFulfillment *bool              `json:"is_expedited_fulfillment,omitempty"`
	Method                 BulkShippingMethod `json:"method"`
	// The phone number of the recipient
	PhoneNumber *string `json:"phone_number,omitempty" validate:"regexp=^\\\\+[1-9]\\\\d{1,14}$"`
	// The name of the recipient to whom the bulk order will be shipped
	RecipientName        RecipientName `json:"recipient_name"`
	AdditionalProperties map[string]interface{}
}

type _BulkShipping BulkShipping

// NewBulkShipping instantiates a new BulkShipping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkShipping(address Address, method BulkShippingMethod, recipientName RecipientName) *BulkShipping {
	this := BulkShipping{}
	this.Address = address
	this.Method = method
	this.RecipientName = recipientName
	return &this
}

// NewBulkShippingWithDefaults instantiates a new BulkShipping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkShippingWithDefaults() *BulkShipping {
	this := BulkShipping{}
	var method BulkShippingMethod = BULKSHIPPINGMETHOD_TWO_DAY
	this.Method = method
	return &this
}

// GetAddress returns the Address field value
func (o *BulkShipping) GetAddress() Address {
	if o == nil {
		var ret Address
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *BulkShipping) GetAddressOk() (*Address, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *BulkShipping) SetAddress(v Address) {
	o.Address = v
}

// GetBusinessName returns the BusinessName field value if set, zero value otherwise.
func (o *BulkShipping) GetBusinessName() string {
	if o == nil || IsNil(o.BusinessName) {
		var ret string
		return ret
	}
	return *o.BusinessName
}

// GetBusinessNameOk returns a tuple with the BusinessName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkShipping) GetBusinessNameOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessName) {
		return nil, false
	}
	return o.BusinessName, true
}

// HasBusinessName returns a boolean if a field has been set.
func (o *BulkShipping) HasBusinessName() bool {
	if o != nil && !IsNil(o.BusinessName) {
		return true
	}

	return false
}

// SetBusinessName gets a reference to the given string and assigns it to the BusinessName field.
func (o *BulkShipping) SetBusinessName(v string) {
	o.BusinessName = &v
}

// GetIsExpeditedFulfillment returns the IsExpeditedFulfillment field value if set, zero value otherwise.
// Deprecated
func (o *BulkShipping) GetIsExpeditedFulfillment() bool {
	if o == nil || IsNil(o.IsExpeditedFulfillment) {
		var ret bool
		return ret
	}
	return *o.IsExpeditedFulfillment
}

// GetIsExpeditedFulfillmentOk returns a tuple with the IsExpeditedFulfillment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *BulkShipping) GetIsExpeditedFulfillmentOk() (*bool, bool) {
	if o == nil || IsNil(o.IsExpeditedFulfillment) {
		return nil, false
	}
	return o.IsExpeditedFulfillment, true
}

// HasIsExpeditedFulfillment returns a boolean if a field has been set.
func (o *BulkShipping) HasIsExpeditedFulfillment() bool {
	if o != nil && !IsNil(o.IsExpeditedFulfillment) {
		return true
	}

	return false
}

// SetIsExpeditedFulfillment gets a reference to the given bool and assigns it to the IsExpeditedFulfillment field.
// Deprecated
func (o *BulkShipping) SetIsExpeditedFulfillment(v bool) {
	o.IsExpeditedFulfillment = &v
}

// GetMethod returns the Method field value
func (o *BulkShipping) GetMethod() BulkShippingMethod {
	if o == nil {
		var ret BulkShippingMethod
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *BulkShipping) GetMethodOk() (*BulkShippingMethod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *BulkShipping) SetMethod(v BulkShippingMethod) {
	o.Method = v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *BulkShipping) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkShipping) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *BulkShipping) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *BulkShipping) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetRecipientName returns the RecipientName field value
func (o *BulkShipping) GetRecipientName() RecipientName {
	if o == nil {
		var ret RecipientName
		return ret
	}

	return o.RecipientName
}

// GetRecipientNameOk returns a tuple with the RecipientName field value
// and a boolean to check if the value has been set.
func (o *BulkShipping) GetRecipientNameOk() (*RecipientName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecipientName, true
}

// SetRecipientName sets field value
func (o *BulkShipping) SetRecipientName(v RecipientName) {
	o.RecipientName = v
}

func (o BulkShipping) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkShipping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	if !IsNil(o.BusinessName) {
		toSerialize["business_name"] = o.BusinessName
	}
	if !IsNil(o.IsExpeditedFulfillment) {
		toSerialize["is_expedited_fulfillment"] = o.IsExpeditedFulfillment
	}
	toSerialize["method"] = o.Method
	if !IsNil(o.PhoneNumber) {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	toSerialize["recipient_name"] = o.RecipientName

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkShipping) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"method",
		"recipient_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkShipping := _BulkShipping{}

	err = json.Unmarshal(data, &varBulkShipping)

	if err != nil {
		return err
	}

	*o = BulkShipping(varBulkShipping)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "business_name")
		delete(additionalProperties, "is_expedited_fulfillment")
		delete(additionalProperties, "method")
		delete(additionalProperties, "phone_number")
		delete(additionalProperties, "recipient_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkShipping struct {
	value *BulkShipping
	isSet bool
}

func (v NullableBulkShipping) Get() *BulkShipping {
	return v.value
}

func (v *NullableBulkShipping) Set(val *BulkShipping) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkShipping) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkShipping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkShipping(val *BulkShipping) *NullableBulkShipping {
	return &NullableBulkShipping{value: val, isSet: true}
}

func (v NullableBulkShipping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkShipping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
