/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
)

// checks if the CreditApplicationPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditApplicationPatch{}

// CreditApplicationPatch struct for CreditApplicationPatch
type CreditApplicationPatch struct {
	Applicants           []Applicant              `json:"applicants,omitempty"`
	Status               *CreditApplicationStatus `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreditApplicationPatch CreditApplicationPatch

// NewCreditApplicationPatch instantiates a new CreditApplicationPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditApplicationPatch() *CreditApplicationPatch {
	this := CreditApplicationPatch{}
	return &this
}

// NewCreditApplicationPatchWithDefaults instantiates a new CreditApplicationPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditApplicationPatchWithDefaults() *CreditApplicationPatch {
	this := CreditApplicationPatch{}
	return &this
}

// GetApplicants returns the Applicants field value if set, zero value otherwise.
func (o *CreditApplicationPatch) GetApplicants() []Applicant {
	if o == nil || IsNil(o.Applicants) {
		var ret []Applicant
		return ret
	}
	return o.Applicants
}

// GetApplicantsOk returns a tuple with the Applicants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditApplicationPatch) GetApplicantsOk() ([]Applicant, bool) {
	if o == nil || IsNil(o.Applicants) {
		return nil, false
	}
	return o.Applicants, true
}

// HasApplicants returns a boolean if a field has been set.
func (o *CreditApplicationPatch) HasApplicants() bool {
	if o != nil && !IsNil(o.Applicants) {
		return true
	}

	return false
}

// SetApplicants gets a reference to the given []Applicant and assigns it to the Applicants field.
func (o *CreditApplicationPatch) SetApplicants(v []Applicant) {
	o.Applicants = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreditApplicationPatch) GetStatus() CreditApplicationStatus {
	if o == nil || IsNil(o.Status) {
		var ret CreditApplicationStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditApplicationPatch) GetStatusOk() (*CreditApplicationStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreditApplicationPatch) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given CreditApplicationStatus and assigns it to the Status field.
func (o *CreditApplicationPatch) SetStatus(v CreditApplicationStatus) {
	o.Status = &v
}

func (o CreditApplicationPatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditApplicationPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Applicants) {
		toSerialize["applicants"] = o.Applicants
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreditApplicationPatch) UnmarshalJSON(data []byte) (err error) {
	varCreditApplicationPatch := _CreditApplicationPatch{}

	err = json.Unmarshal(data, &varCreditApplicationPatch)

	if err != nil {
		return err
	}

	*o = CreditApplicationPatch(varCreditApplicationPatch)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "applicants")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreditApplicationPatch struct {
	value *CreditApplicationPatch
	isSet bool
}

func (v NullableCreditApplicationPatch) Get() *CreditApplicationPatch {
	return v.value
}

func (v *NullableCreditApplicationPatch) Set(val *CreditApplicationPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditApplicationPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditApplicationPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditApplicationPatch(val *CreditApplicationPatch) *NullableCreditApplicationPatch {
	return &NullableCreditApplicationPatch{value: val, isSet: true}
}

func (v NullableCreditApplicationPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditApplicationPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
