/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
)

// checks if the TemplateFieldsLineOfCredit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateFieldsLineOfCredit{}

// TemplateFieldsLineOfCredit struct for TemplateFieldsLineOfCredit
type TemplateFieldsLineOfCredit struct {
	AccountProgramId *string     `json:"account_program_id,omitempty"`
	AccountType      AccountType `json:"account_type"`
	// The bank account ID for this account. This is a unique identifier for the bank side account that this Synctera account belongs to. This field can be auto filled if only one bank account of the appropriate type exist for the tenant of concern.
	BankAccountId *string `json:"bank_account_id,omitempty"`
	// Bank country of the account. ISO 3166-1 Alpha-2 or Alpha-3 country code.
	BankCountry string `json:"bank_country" validate:"regexp=^[A-Z]{2,3}$"`
	// Account currency. ISO 4217 alphabetic currency code
	Currency string `json:"currency" validate:"regexp=^[A-Z]{3}$"`
	// The number of days past the billing period to allow for payment before it is considered due. This directly determines the due date for a payment.
	GracePeriod *int32 `json:"grace_period,omitempty"`
	// An interest account product that the current account associates with. The account product must have its calculation_method set to COMPOUNDED_DAILY.
	InterestProductId    *string                        `json:"interest_product_id,omitempty"`
	MinimumPayment       MinimumPaymentTypeRateOrAmount `json:"minimum_payment"`
	AdditionalProperties map[string]interface{}
}

type _TemplateFieldsLineOfCredit TemplateFieldsLineOfCredit

// NewTemplateFieldsLineOfCredit instantiates a new TemplateFieldsLineOfCredit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateFieldsLineOfCredit(accountType AccountType, bankCountry string, currency string, minimumPayment MinimumPaymentTypeRateOrAmount) *TemplateFieldsLineOfCredit {
	this := TemplateFieldsLineOfCredit{}
	this.AccountType = accountType
	this.BankCountry = bankCountry
	this.Currency = currency
	this.MinimumPayment = minimumPayment
	return &this
}

// NewTemplateFieldsLineOfCreditWithDefaults instantiates a new TemplateFieldsLineOfCredit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateFieldsLineOfCreditWithDefaults() *TemplateFieldsLineOfCredit {
	this := TemplateFieldsLineOfCredit{}
	return &this
}

// GetAccountProgramId returns the AccountProgramId field value if set, zero value otherwise.
func (o *TemplateFieldsLineOfCredit) GetAccountProgramId() string {
	if o == nil || IsNil(o.AccountProgramId) {
		var ret string
		return ret
	}
	return *o.AccountProgramId
}

// GetAccountProgramIdOk returns a tuple with the AccountProgramId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateFieldsLineOfCredit) GetAccountProgramIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountProgramId) {
		return nil, false
	}
	return o.AccountProgramId, true
}

// HasAccountProgramId returns a boolean if a field has been set.
func (o *TemplateFieldsLineOfCredit) HasAccountProgramId() bool {
	if o != nil && !IsNil(o.AccountProgramId) {
		return true
	}

	return false
}

// SetAccountProgramId gets a reference to the given string and assigns it to the AccountProgramId field.
func (o *TemplateFieldsLineOfCredit) SetAccountProgramId(v string) {
	o.AccountProgramId = &v
}

// GetAccountType returns the AccountType field value
func (o *TemplateFieldsLineOfCredit) GetAccountType() AccountType {
	if o == nil {
		var ret AccountType
		return ret
	}

	return o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value
// and a boolean to check if the value has been set.
func (o *TemplateFieldsLineOfCredit) GetAccountTypeOk() (*AccountType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountType, true
}

// SetAccountType sets field value
func (o *TemplateFieldsLineOfCredit) SetAccountType(v AccountType) {
	o.AccountType = v
}

// GetBankAccountId returns the BankAccountId field value if set, zero value otherwise.
func (o *TemplateFieldsLineOfCredit) GetBankAccountId() string {
	if o == nil || IsNil(o.BankAccountId) {
		var ret string
		return ret
	}
	return *o.BankAccountId
}

// GetBankAccountIdOk returns a tuple with the BankAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateFieldsLineOfCredit) GetBankAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.BankAccountId) {
		return nil, false
	}
	return o.BankAccountId, true
}

// HasBankAccountId returns a boolean if a field has been set.
func (o *TemplateFieldsLineOfCredit) HasBankAccountId() bool {
	if o != nil && !IsNil(o.BankAccountId) {
		return true
	}

	return false
}

// SetBankAccountId gets a reference to the given string and assigns it to the BankAccountId field.
func (o *TemplateFieldsLineOfCredit) SetBankAccountId(v string) {
	o.BankAccountId = &v
}

// GetBankCountry returns the BankCountry field value
func (o *TemplateFieldsLineOfCredit) GetBankCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankCountry
}

// GetBankCountryOk returns a tuple with the BankCountry field value
// and a boolean to check if the value has been set.
func (o *TemplateFieldsLineOfCredit) GetBankCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankCountry, true
}

// SetBankCountry sets field value
func (o *TemplateFieldsLineOfCredit) SetBankCountry(v string) {
	o.BankCountry = v
}

// GetCurrency returns the Currency field value
func (o *TemplateFieldsLineOfCredit) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *TemplateFieldsLineOfCredit) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *TemplateFieldsLineOfCredit) SetCurrency(v string) {
	o.Currency = v
}

// GetGracePeriod returns the GracePeriod field value if set, zero value otherwise.
func (o *TemplateFieldsLineOfCredit) GetGracePeriod() int32 {
	if o == nil || IsNil(o.GracePeriod) {
		var ret int32
		return ret
	}
	return *o.GracePeriod
}

// GetGracePeriodOk returns a tuple with the GracePeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateFieldsLineOfCredit) GetGracePeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.GracePeriod) {
		return nil, false
	}
	return o.GracePeriod, true
}

// HasGracePeriod returns a boolean if a field has been set.
func (o *TemplateFieldsLineOfCredit) HasGracePeriod() bool {
	if o != nil && !IsNil(o.GracePeriod) {
		return true
	}

	return false
}

// SetGracePeriod gets a reference to the given int32 and assigns it to the GracePeriod field.
func (o *TemplateFieldsLineOfCredit) SetGracePeriod(v int32) {
	o.GracePeriod = &v
}

// GetInterestProductId returns the InterestProductId field value if set, zero value otherwise.
func (o *TemplateFieldsLineOfCredit) GetInterestProductId() string {
	if o == nil || IsNil(o.InterestProductId) {
		var ret string
		return ret
	}
	return *o.InterestProductId
}

// GetInterestProductIdOk returns a tuple with the InterestProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateFieldsLineOfCredit) GetInterestProductIdOk() (*string, bool) {
	if o == nil || IsNil(o.InterestProductId) {
		return nil, false
	}
	return o.InterestProductId, true
}

// HasInterestProductId returns a boolean if a field has been set.
func (o *TemplateFieldsLineOfCredit) HasInterestProductId() bool {
	if o != nil && !IsNil(o.InterestProductId) {
		return true
	}

	return false
}

// SetInterestProductId gets a reference to the given string and assigns it to the InterestProductId field.
func (o *TemplateFieldsLineOfCredit) SetInterestProductId(v string) {
	o.InterestProductId = &v
}

// GetMinimumPayment returns the MinimumPayment field value
func (o *TemplateFieldsLineOfCredit) GetMinimumPayment() MinimumPaymentTypeRateOrAmount {
	if o == nil {
		var ret MinimumPaymentTypeRateOrAmount
		return ret
	}

	return o.MinimumPayment
}

// GetMinimumPaymentOk returns a tuple with the MinimumPayment field value
// and a boolean to check if the value has been set.
func (o *TemplateFieldsLineOfCredit) GetMinimumPaymentOk() (*MinimumPaymentTypeRateOrAmount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinimumPayment, true
}

// SetMinimumPayment sets field value
func (o *TemplateFieldsLineOfCredit) SetMinimumPayment(v MinimumPaymentTypeRateOrAmount) {
	o.MinimumPayment = v
}

func (o TemplateFieldsLineOfCredit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateFieldsLineOfCredit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountProgramId) {
		toSerialize["account_program_id"] = o.AccountProgramId
	}
	toSerialize["account_type"] = o.AccountType
	if !IsNil(o.BankAccountId) {
		toSerialize["bank_account_id"] = o.BankAccountId
	}
	toSerialize["bank_country"] = o.BankCountry
	toSerialize["currency"] = o.Currency
	if !IsNil(o.GracePeriod) {
		toSerialize["grace_period"] = o.GracePeriod
	}
	if !IsNil(o.InterestProductId) {
		toSerialize["interest_product_id"] = o.InterestProductId
	}
	toSerialize["minimum_payment"] = o.MinimumPayment

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TemplateFieldsLineOfCredit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_type",
		"bank_country",
		"currency",
		"minimum_payment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateFieldsLineOfCredit := _TemplateFieldsLineOfCredit{}

	err = json.Unmarshal(data, &varTemplateFieldsLineOfCredit)

	if err != nil {
		return err
	}

	*o = TemplateFieldsLineOfCredit(varTemplateFieldsLineOfCredit)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account_program_id")
		delete(additionalProperties, "account_type")
		delete(additionalProperties, "bank_account_id")
		delete(additionalProperties, "bank_country")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "grace_period")
		delete(additionalProperties, "interest_product_id")
		delete(additionalProperties, "minimum_payment")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTemplateFieldsLineOfCredit struct {
	value *TemplateFieldsLineOfCredit
	isSet bool
}

func (v NullableTemplateFieldsLineOfCredit) Get() *TemplateFieldsLineOfCredit {
	return v.value
}

func (v *NullableTemplateFieldsLineOfCredit) Set(val *TemplateFieldsLineOfCredit) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateFieldsLineOfCredit) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateFieldsLineOfCredit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateFieldsLineOfCredit(val *TemplateFieldsLineOfCredit) *NullableTemplateFieldsLineOfCredit {
	return &NullableTemplateFieldsLineOfCredit{value: val, isSet: true}
}

func (v NullableTemplateFieldsLineOfCredit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateFieldsLineOfCredit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
