/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
)

// DisputeActionBy | action_by | Description                                                                                            | |-----------|--------------------------------------------------------------------------------------------------------| | INITIATOR | The last action was taken by the initiator of the dispute.                                             | | NETWORK   | The last action was taken by the network.                                                              |
type DisputeActionBy string

// List of dispute_action_by
const (
	DISPUTEACTIONBY_NETWORK   DisputeActionBy = "NETWORK"
	DISPUTEACTIONBY_INITIATOR DisputeActionBy = "INITIATOR"
)

// All allowed values of DisputeActionBy enum
var AllowedDisputeActionByEnumValues = []DisputeActionBy{
	"NETWORK",
	"INITIATOR",
}

func (v *DisputeActionBy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DisputeActionBy(value)
	for _, existing := range AllowedDisputeActionByEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DisputeActionBy", value)
}

// NewDisputeActionByFromValue returns a pointer to a valid DisputeActionBy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDisputeActionByFromValue(v string) (*DisputeActionBy, error) {
	ev := DisputeActionBy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DisputeActionBy: valid values are %v", v, AllowedDisputeActionByEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DisputeActionBy) IsValid() bool {
	for _, existing := range AllowedDisputeActionByEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to dispute_action_by value
func (v DisputeActionBy) Ptr() *DisputeActionBy {
	return &v
}

type NullableDisputeActionBy struct {
	value *DisputeActionBy
	isSet bool
}

func (v NullableDisputeActionBy) Get() *DisputeActionBy {
	return v.value
}

func (v *NullableDisputeActionBy) Set(val *DisputeActionBy) {
	v.value = val
	v.isSet = true
}

func (v NullableDisputeActionBy) IsSet() bool {
	return v.isSet
}

func (v *NullableDisputeActionBy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisputeActionBy(val *DisputeActionBy) *NullableDisputeActionBy {
	return &NullableDisputeActionBy{value: val, isSet: true}
}

func (v NullableDisputeActionBy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisputeActionBy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
