/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
)

// FdxTokenType The type of the FDX token.
type FdxTokenType string

// List of fdx_token_type
const (
	FDXTOKENTYPE_ACCESS  FdxTokenType = "ACCESS"
	FDXTOKENTYPE_REFRESH FdxTokenType = "REFRESH"
)

// All allowed values of FdxTokenType enum
var AllowedFdxTokenTypeEnumValues = []FdxTokenType{
	"ACCESS",
	"REFRESH",
}

func (v *FdxTokenType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FdxTokenType(value)
	for _, existing := range AllowedFdxTokenTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FdxTokenType", value)
}

// NewFdxTokenTypeFromValue returns a pointer to a valid FdxTokenType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFdxTokenTypeFromValue(v string) (*FdxTokenType, error) {
	ev := FdxTokenType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FdxTokenType: valid values are %v", v, AllowedFdxTokenTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FdxTokenType) IsValid() bool {
	for _, existing := range AllowedFdxTokenTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to fdx_token_type value
func (v FdxTokenType) Ptr() *FdxTokenType {
	return &v
}

type NullableFdxTokenType struct {
	value *FdxTokenType
	isSet bool
}

func (v NullableFdxTokenType) Get() *FdxTokenType {
	return v.value
}

func (v *NullableFdxTokenType) Set(val *FdxTokenType) {
	v.value = val
	v.isSet = true
}

func (v NullableFdxTokenType) IsSet() bool {
	return v.isSet
}

func (v *NullableFdxTokenType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFdxTokenType(val *FdxTokenType) *NullableFdxTokenType {
	return &NullableFdxTokenType{value: val, isSet: true}
}

func (v NullableFdxTokenType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFdxTokenType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
