/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CardDisputeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CardDisputeResponse{}

// CardDisputeResponse Response for a card dispute.
type CardDisputeResponse struct {
	// The customer account related to the dispute, to which dispute-related credits will be posted.
	AccountId            string             `json:"account_id"`
	ApplicableRegulation *DisputeRegulation `json:"applicable_regulation,omitempty"`
	// The timestamp representing when the dispute was created
	CreationTime time.Time `json:"creation_time"`
	// ISO 4217 Alpha-3 currency code
	Currency string `json:"currency"`
	// The customer related to the dispute, to which dispute-related credits will be posted.
	CustomerId string `json:"customer_id"`
	// The timestamp representing when the customer reported the dispute.
	DateCustomerReported time.Time       `json:"date_customer_reported"`
	Decision             DisputeDecision `json:"decision"`
	// Documents associated with the dispute.
	DisputeDocuments []DisputeDocumentResponse `json:"dispute_documents"`
	// The amount to be disputed in cents.
	DisputedAmount int32 `json:"disputed_amount"`
	// Reference ID associated with the dispute on the external network.
	ExternalReferenceId *string `json:"external_reference_id,omitempty"`
	// The unique identifier of the dispute
	Id           string           `json:"id"`
	LastActionBy *DisputeActionBy `json:"last_action_by,omitempty"`
	// The timestamp representing when the dispute was last modified
	LastUpdatedTime time.Time `json:"last_updated_time"`
	// Brief written message describing the reason for disputing the transaction.
	Memo        string         `json:"memo"`
	Network     DisputeNetwork `json:"network"`
	PaymentRail PaymentRail    `json:"payment_rail"`
	Status      DisputeStatus  `json:"status"`
	// The id of the tenant containing the resource.
	Tenant string `json:"tenant"`
	// The time that a final decision was made on the dispute.
	TimestampFinalDecision    *time.Time `json:"timestamp_final_decision,omitempty"`
	TimestampInvestigationDue *time.Time `json:"timestamp_investigation_due,omitempty"`
	// The time by which provisional credit should be posted to the customer account in response to the dispute.
	TimestampProvisionalCreditDue *time.Time `json:"timestamp_provisional_credit_due,omitempty"`
	// The ID of the posted transaction to be disputed.
	TransactionId string `json:"transaction_id"`
	// The acquirer reference number of the original transaction associated with the dispute.
	AcquirerReferenceNumber *string `json:"acquirer_reference_number,omitempty"`
	// History of all the action filed for the dispute.
	ActionHistory []CardDisputeActionResponse `json:"action_history"`
	// List of actions that can be taken on the dispute.
	AvailableActions   []AvailableCardAction  `json:"available_actions"`
	CreditStatus       DisputeCreditStatus    `json:"credit_status"`
	LifecycleState     CardLifecycleState     `json:"lifecycle_state"`
	ManagedBy          CardDisputeManagedBy   `json:"managed_by"`
	NetworkEligibility CardNetworkEligibility `json:"network_eligibility"`
	ReasonCode         CardDisputeReasonCodes `json:"reason_code"`
	// The switch serial number of the original transaction associated with the dispute.
	SwitchSerialNumber   *string `json:"switch_serial_number,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CardDisputeResponse CardDisputeResponse

// NewCardDisputeResponse instantiates a new CardDisputeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardDisputeResponse(accountId string, creationTime time.Time, currency string, customerId string, dateCustomerReported time.Time, decision DisputeDecision, disputeDocuments []DisputeDocumentResponse, disputedAmount int32, id string, lastUpdatedTime time.Time, memo string, network DisputeNetwork, paymentRail PaymentRail, status DisputeStatus, tenant string, transactionId string, actionHistory []CardDisputeActionResponse, availableActions []AvailableCardAction, creditStatus DisputeCreditStatus, lifecycleState CardLifecycleState, managedBy CardDisputeManagedBy, networkEligibility CardNetworkEligibility, reasonCode CardDisputeReasonCodes) *CardDisputeResponse {
	this := CardDisputeResponse{}
	this.AccountId = accountId
	this.CreationTime = creationTime
	this.Currency = currency
	this.CustomerId = customerId
	this.DateCustomerReported = dateCustomerReported
	this.Decision = decision
	this.DisputeDocuments = disputeDocuments
	this.DisputedAmount = disputedAmount
	this.Id = id
	this.LastUpdatedTime = lastUpdatedTime
	this.Memo = memo
	this.Network = network
	this.PaymentRail = paymentRail
	this.Status = status
	this.Tenant = tenant
	this.TransactionId = transactionId
	this.ActionHistory = actionHistory
	this.AvailableActions = availableActions
	this.CreditStatus = creditStatus
	this.LifecycleState = lifecycleState
	this.ManagedBy = managedBy
	this.NetworkEligibility = networkEligibility
	this.ReasonCode = reasonCode
	return &this
}

// NewCardDisputeResponseWithDefaults instantiates a new CardDisputeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardDisputeResponseWithDefaults() *CardDisputeResponse {
	this := CardDisputeResponse{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *CardDisputeResponse) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CardDisputeResponse) SetAccountId(v string) {
	o.AccountId = v
}

// GetApplicableRegulation returns the ApplicableRegulation field value if set, zero value otherwise.
func (o *CardDisputeResponse) GetApplicableRegulation() DisputeRegulation {
	if o == nil || IsNil(o.ApplicableRegulation) {
		var ret DisputeRegulation
		return ret
	}
	return *o.ApplicableRegulation
}

// GetApplicableRegulationOk returns a tuple with the ApplicableRegulation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetApplicableRegulationOk() (*DisputeRegulation, bool) {
	if o == nil || IsNil(o.ApplicableRegulation) {
		return nil, false
	}
	return o.ApplicableRegulation, true
}

// HasApplicableRegulation returns a boolean if a field has been set.
func (o *CardDisputeResponse) HasApplicableRegulation() bool {
	if o != nil && !IsNil(o.ApplicableRegulation) {
		return true
	}

	return false
}

// SetApplicableRegulation gets a reference to the given DisputeRegulation and assigns it to the ApplicableRegulation field.
func (o *CardDisputeResponse) SetApplicableRegulation(v DisputeRegulation) {
	o.ApplicableRegulation = &v
}

// GetCreationTime returns the CreationTime field value
func (o *CardDisputeResponse) GetCreationTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetCreationTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreationTime, true
}

// SetCreationTime sets field value
func (o *CardDisputeResponse) SetCreationTime(v time.Time) {
	o.CreationTime = v
}

// GetCurrency returns the Currency field value
func (o *CardDisputeResponse) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *CardDisputeResponse) SetCurrency(v string) {
	o.Currency = v
}

// GetCustomerId returns the CustomerId field value
func (o *CardDisputeResponse) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *CardDisputeResponse) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetDateCustomerReported returns the DateCustomerReported field value
func (o *CardDisputeResponse) GetDateCustomerReported() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.DateCustomerReported
}

// GetDateCustomerReportedOk returns a tuple with the DateCustomerReported field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetDateCustomerReportedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DateCustomerReported, true
}

// SetDateCustomerReported sets field value
func (o *CardDisputeResponse) SetDateCustomerReported(v time.Time) {
	o.DateCustomerReported = v
}

// GetDecision returns the Decision field value
func (o *CardDisputeResponse) GetDecision() DisputeDecision {
	if o == nil {
		var ret DisputeDecision
		return ret
	}

	return o.Decision
}

// GetDecisionOk returns a tuple with the Decision field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetDecisionOk() (*DisputeDecision, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decision, true
}

// SetDecision sets field value
func (o *CardDisputeResponse) SetDecision(v DisputeDecision) {
	o.Decision = v
}

// GetDisputeDocuments returns the DisputeDocuments field value
func (o *CardDisputeResponse) GetDisputeDocuments() []DisputeDocumentResponse {
	if o == nil {
		var ret []DisputeDocumentResponse
		return ret
	}

	return o.DisputeDocuments
}

// GetDisputeDocumentsOk returns a tuple with the DisputeDocuments field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetDisputeDocumentsOk() ([]DisputeDocumentResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisputeDocuments, true
}

// SetDisputeDocuments sets field value
func (o *CardDisputeResponse) SetDisputeDocuments(v []DisputeDocumentResponse) {
	o.DisputeDocuments = v
}

// GetDisputedAmount returns the DisputedAmount field value
func (o *CardDisputeResponse) GetDisputedAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DisputedAmount
}

// GetDisputedAmountOk returns a tuple with the DisputedAmount field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetDisputedAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisputedAmount, true
}

// SetDisputedAmount sets field value
func (o *CardDisputeResponse) SetDisputedAmount(v int32) {
	o.DisputedAmount = v
}

// GetExternalReferenceId returns the ExternalReferenceId field value if set, zero value otherwise.
func (o *CardDisputeResponse) GetExternalReferenceId() string {
	if o == nil || IsNil(o.ExternalReferenceId) {
		var ret string
		return ret
	}
	return *o.ExternalReferenceId
}

// GetExternalReferenceIdOk returns a tuple with the ExternalReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetExternalReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalReferenceId) {
		return nil, false
	}
	return o.ExternalReferenceId, true
}

// HasExternalReferenceId returns a boolean if a field has been set.
func (o *CardDisputeResponse) HasExternalReferenceId() bool {
	if o != nil && !IsNil(o.ExternalReferenceId) {
		return true
	}

	return false
}

// SetExternalReferenceId gets a reference to the given string and assigns it to the ExternalReferenceId field.
func (o *CardDisputeResponse) SetExternalReferenceId(v string) {
	o.ExternalReferenceId = &v
}

// GetId returns the Id field value
func (o *CardDisputeResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CardDisputeResponse) SetId(v string) {
	o.Id = v
}

// GetLastActionBy returns the LastActionBy field value if set, zero value otherwise.
func (o *CardDisputeResponse) GetLastActionBy() DisputeActionBy {
	if o == nil || IsNil(o.LastActionBy) {
		var ret DisputeActionBy
		return ret
	}
	return *o.LastActionBy
}

// GetLastActionByOk returns a tuple with the LastActionBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetLastActionByOk() (*DisputeActionBy, bool) {
	if o == nil || IsNil(o.LastActionBy) {
		return nil, false
	}
	return o.LastActionBy, true
}

// HasLastActionBy returns a boolean if a field has been set.
func (o *CardDisputeResponse) HasLastActionBy() bool {
	if o != nil && !IsNil(o.LastActionBy) {
		return true
	}

	return false
}

// SetLastActionBy gets a reference to the given DisputeActionBy and assigns it to the LastActionBy field.
func (o *CardDisputeResponse) SetLastActionBy(v DisputeActionBy) {
	o.LastActionBy = &v
}

// GetLastUpdatedTime returns the LastUpdatedTime field value
func (o *CardDisputeResponse) GetLastUpdatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUpdatedTime
}

// GetLastUpdatedTimeOk returns a tuple with the LastUpdatedTime field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetLastUpdatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdatedTime, true
}

// SetLastUpdatedTime sets field value
func (o *CardDisputeResponse) SetLastUpdatedTime(v time.Time) {
	o.LastUpdatedTime = v
}

// GetMemo returns the Memo field value
func (o *CardDisputeResponse) GetMemo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Memo
}

// GetMemoOk returns a tuple with the Memo field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetMemoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Memo, true
}

// SetMemo sets field value
func (o *CardDisputeResponse) SetMemo(v string) {
	o.Memo = v
}

// GetNetwork returns the Network field value
func (o *CardDisputeResponse) GetNetwork() DisputeNetwork {
	if o == nil {
		var ret DisputeNetwork
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetNetworkOk() (*DisputeNetwork, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *CardDisputeResponse) SetNetwork(v DisputeNetwork) {
	o.Network = v
}

// GetPaymentRail returns the PaymentRail field value
func (o *CardDisputeResponse) GetPaymentRail() PaymentRail {
	if o == nil {
		var ret PaymentRail
		return ret
	}

	return o.PaymentRail
}

// GetPaymentRailOk returns a tuple with the PaymentRail field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetPaymentRailOk() (*PaymentRail, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentRail, true
}

// SetPaymentRail sets field value
func (o *CardDisputeResponse) SetPaymentRail(v PaymentRail) {
	o.PaymentRail = v
}

// GetStatus returns the Status field value
func (o *CardDisputeResponse) GetStatus() DisputeStatus {
	if o == nil {
		var ret DisputeStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetStatusOk() (*DisputeStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CardDisputeResponse) SetStatus(v DisputeStatus) {
	o.Status = v
}

// GetTenant returns the Tenant field value
func (o *CardDisputeResponse) GetTenant() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetTenantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tenant, true
}

// SetTenant sets field value
func (o *CardDisputeResponse) SetTenant(v string) {
	o.Tenant = v
}

// GetTimestampFinalDecision returns the TimestampFinalDecision field value if set, zero value otherwise.
func (o *CardDisputeResponse) GetTimestampFinalDecision() time.Time {
	if o == nil || IsNil(o.TimestampFinalDecision) {
		var ret time.Time
		return ret
	}
	return *o.TimestampFinalDecision
}

// GetTimestampFinalDecisionOk returns a tuple with the TimestampFinalDecision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetTimestampFinalDecisionOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TimestampFinalDecision) {
		return nil, false
	}
	return o.TimestampFinalDecision, true
}

// HasTimestampFinalDecision returns a boolean if a field has been set.
func (o *CardDisputeResponse) HasTimestampFinalDecision() bool {
	if o != nil && !IsNil(o.TimestampFinalDecision) {
		return true
	}

	return false
}

// SetTimestampFinalDecision gets a reference to the given time.Time and assigns it to the TimestampFinalDecision field.
func (o *CardDisputeResponse) SetTimestampFinalDecision(v time.Time) {
	o.TimestampFinalDecision = &v
}

// GetTimestampInvestigationDue returns the TimestampInvestigationDue field value if set, zero value otherwise.
func (o *CardDisputeResponse) GetTimestampInvestigationDue() time.Time {
	if o == nil || IsNil(o.TimestampInvestigationDue) {
		var ret time.Time
		return ret
	}
	return *o.TimestampInvestigationDue
}

// GetTimestampInvestigationDueOk returns a tuple with the TimestampInvestigationDue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetTimestampInvestigationDueOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TimestampInvestigationDue) {
		return nil, false
	}
	return o.TimestampInvestigationDue, true
}

// HasTimestampInvestigationDue returns a boolean if a field has been set.
func (o *CardDisputeResponse) HasTimestampInvestigationDue() bool {
	if o != nil && !IsNil(o.TimestampInvestigationDue) {
		return true
	}

	return false
}

// SetTimestampInvestigationDue gets a reference to the given time.Time and assigns it to the TimestampInvestigationDue field.
func (o *CardDisputeResponse) SetTimestampInvestigationDue(v time.Time) {
	o.TimestampInvestigationDue = &v
}

// GetTimestampProvisionalCreditDue returns the TimestampProvisionalCreditDue field value if set, zero value otherwise.
func (o *CardDisputeResponse) GetTimestampProvisionalCreditDue() time.Time {
	if o == nil || IsNil(o.TimestampProvisionalCreditDue) {
		var ret time.Time
		return ret
	}
	return *o.TimestampProvisionalCreditDue
}

// GetTimestampProvisionalCreditDueOk returns a tuple with the TimestampProvisionalCreditDue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetTimestampProvisionalCreditDueOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TimestampProvisionalCreditDue) {
		return nil, false
	}
	return o.TimestampProvisionalCreditDue, true
}

// HasTimestampProvisionalCreditDue returns a boolean if a field has been set.
func (o *CardDisputeResponse) HasTimestampProvisionalCreditDue() bool {
	if o != nil && !IsNil(o.TimestampProvisionalCreditDue) {
		return true
	}

	return false
}

// SetTimestampProvisionalCreditDue gets a reference to the given time.Time and assigns it to the TimestampProvisionalCreditDue field.
func (o *CardDisputeResponse) SetTimestampProvisionalCreditDue(v time.Time) {
	o.TimestampProvisionalCreditDue = &v
}

// GetTransactionId returns the TransactionId field value
func (o *CardDisputeResponse) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *CardDisputeResponse) SetTransactionId(v string) {
	o.TransactionId = v
}

// GetAcquirerReferenceNumber returns the AcquirerReferenceNumber field value if set, zero value otherwise.
func (o *CardDisputeResponse) GetAcquirerReferenceNumber() string {
	if o == nil || IsNil(o.AcquirerReferenceNumber) {
		var ret string
		return ret
	}
	return *o.AcquirerReferenceNumber
}

// GetAcquirerReferenceNumberOk returns a tuple with the AcquirerReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetAcquirerReferenceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.AcquirerReferenceNumber) {
		return nil, false
	}
	return o.AcquirerReferenceNumber, true
}

// HasAcquirerReferenceNumber returns a boolean if a field has been set.
func (o *CardDisputeResponse) HasAcquirerReferenceNumber() bool {
	if o != nil && !IsNil(o.AcquirerReferenceNumber) {
		return true
	}

	return false
}

// SetAcquirerReferenceNumber gets a reference to the given string and assigns it to the AcquirerReferenceNumber field.
func (o *CardDisputeResponse) SetAcquirerReferenceNumber(v string) {
	o.AcquirerReferenceNumber = &v
}

// GetActionHistory returns the ActionHistory field value
func (o *CardDisputeResponse) GetActionHistory() []CardDisputeActionResponse {
	if o == nil {
		var ret []CardDisputeActionResponse
		return ret
	}

	return o.ActionHistory
}

// GetActionHistoryOk returns a tuple with the ActionHistory field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetActionHistoryOk() ([]CardDisputeActionResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActionHistory, true
}

// SetActionHistory sets field value
func (o *CardDisputeResponse) SetActionHistory(v []CardDisputeActionResponse) {
	o.ActionHistory = v
}

// GetAvailableActions returns the AvailableActions field value
func (o *CardDisputeResponse) GetAvailableActions() []AvailableCardAction {
	if o == nil {
		var ret []AvailableCardAction
		return ret
	}

	return o.AvailableActions
}

// GetAvailableActionsOk returns a tuple with the AvailableActions field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetAvailableActionsOk() ([]AvailableCardAction, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvailableActions, true
}

// SetAvailableActions sets field value
func (o *CardDisputeResponse) SetAvailableActions(v []AvailableCardAction) {
	o.AvailableActions = v
}

// GetCreditStatus returns the CreditStatus field value
func (o *CardDisputeResponse) GetCreditStatus() DisputeCreditStatus {
	if o == nil {
		var ret DisputeCreditStatus
		return ret
	}

	return o.CreditStatus
}

// GetCreditStatusOk returns a tuple with the CreditStatus field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetCreditStatusOk() (*DisputeCreditStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditStatus, true
}

// SetCreditStatus sets field value
func (o *CardDisputeResponse) SetCreditStatus(v DisputeCreditStatus) {
	o.CreditStatus = v
}

// GetLifecycleState returns the LifecycleState field value
func (o *CardDisputeResponse) GetLifecycleState() CardLifecycleState {
	if o == nil {
		var ret CardLifecycleState
		return ret
	}

	return o.LifecycleState
}

// GetLifecycleStateOk returns a tuple with the LifecycleState field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetLifecycleStateOk() (*CardLifecycleState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LifecycleState, true
}

// SetLifecycleState sets field value
func (o *CardDisputeResponse) SetLifecycleState(v CardLifecycleState) {
	o.LifecycleState = v
}

// GetManagedBy returns the ManagedBy field value
func (o *CardDisputeResponse) GetManagedBy() CardDisputeManagedBy {
	if o == nil {
		var ret CardDisputeManagedBy
		return ret
	}

	return o.ManagedBy
}

// GetManagedByOk returns a tuple with the ManagedBy field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetManagedByOk() (*CardDisputeManagedBy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManagedBy, true
}

// SetManagedBy sets field value
func (o *CardDisputeResponse) SetManagedBy(v CardDisputeManagedBy) {
	o.ManagedBy = v
}

// GetNetworkEligibility returns the NetworkEligibility field value
func (o *CardDisputeResponse) GetNetworkEligibility() CardNetworkEligibility {
	if o == nil {
		var ret CardNetworkEligibility
		return ret
	}

	return o.NetworkEligibility
}

// GetNetworkEligibilityOk returns a tuple with the NetworkEligibility field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetNetworkEligibilityOk() (*CardNetworkEligibility, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkEligibility, true
}

// SetNetworkEligibility sets field value
func (o *CardDisputeResponse) SetNetworkEligibility(v CardNetworkEligibility) {
	o.NetworkEligibility = v
}

// GetReasonCode returns the ReasonCode field value
func (o *CardDisputeResponse) GetReasonCode() CardDisputeReasonCodes {
	if o == nil {
		var ret CardDisputeReasonCodes
		return ret
	}

	return o.ReasonCode
}

// GetReasonCodeOk returns a tuple with the ReasonCode field value
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetReasonCodeOk() (*CardDisputeReasonCodes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReasonCode, true
}

// SetReasonCode sets field value
func (o *CardDisputeResponse) SetReasonCode(v CardDisputeReasonCodes) {
	o.ReasonCode = v
}

// GetSwitchSerialNumber returns the SwitchSerialNumber field value if set, zero value otherwise.
func (o *CardDisputeResponse) GetSwitchSerialNumber() string {
	if o == nil || IsNil(o.SwitchSerialNumber) {
		var ret string
		return ret
	}
	return *o.SwitchSerialNumber
}

// GetSwitchSerialNumberOk returns a tuple with the SwitchSerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardDisputeResponse) GetSwitchSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SwitchSerialNumber) {
		return nil, false
	}
	return o.SwitchSerialNumber, true
}

// HasSwitchSerialNumber returns a boolean if a field has been set.
func (o *CardDisputeResponse) HasSwitchSerialNumber() bool {
	if o != nil && !IsNil(o.SwitchSerialNumber) {
		return true
	}

	return false
}

// SetSwitchSerialNumber gets a reference to the given string and assigns it to the SwitchSerialNumber field.
func (o *CardDisputeResponse) SetSwitchSerialNumber(v string) {
	o.SwitchSerialNumber = &v
}

func (o CardDisputeResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CardDisputeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	if !IsNil(o.ApplicableRegulation) {
		toSerialize["applicable_regulation"] = o.ApplicableRegulation
	}
	toSerialize["creation_time"] = o.CreationTime
	toSerialize["currency"] = o.Currency
	toSerialize["customer_id"] = o.CustomerId
	toSerialize["date_customer_reported"] = o.DateCustomerReported
	toSerialize["decision"] = o.Decision
	toSerialize["dispute_documents"] = o.DisputeDocuments
	toSerialize["disputed_amount"] = o.DisputedAmount
	if !IsNil(o.ExternalReferenceId) {
		toSerialize["external_reference_id"] = o.ExternalReferenceId
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.LastActionBy) {
		toSerialize["last_action_by"] = o.LastActionBy
	}
	toSerialize["last_updated_time"] = o.LastUpdatedTime
	toSerialize["memo"] = o.Memo
	toSerialize["network"] = o.Network
	toSerialize["payment_rail"] = o.PaymentRail
	toSerialize["status"] = o.Status
	toSerialize["tenant"] = o.Tenant
	if !IsNil(o.TimestampFinalDecision) {
		toSerialize["timestamp_final_decision"] = o.TimestampFinalDecision
	}
	if !IsNil(o.TimestampInvestigationDue) {
		toSerialize["timestamp_investigation_due"] = o.TimestampInvestigationDue
	}
	if !IsNil(o.TimestampProvisionalCreditDue) {
		toSerialize["timestamp_provisional_credit_due"] = o.TimestampProvisionalCreditDue
	}
	toSerialize["transaction_id"] = o.TransactionId
	if !IsNil(o.AcquirerReferenceNumber) {
		toSerialize["acquirer_reference_number"] = o.AcquirerReferenceNumber
	}
	toSerialize["action_history"] = o.ActionHistory
	toSerialize["available_actions"] = o.AvailableActions
	toSerialize["credit_status"] = o.CreditStatus
	toSerialize["lifecycle_state"] = o.LifecycleState
	toSerialize["managed_by"] = o.ManagedBy
	toSerialize["network_eligibility"] = o.NetworkEligibility
	toSerialize["reason_code"] = o.ReasonCode
	if !IsNil(o.SwitchSerialNumber) {
		toSerialize["switch_serial_number"] = o.SwitchSerialNumber
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CardDisputeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"creation_time",
		"currency",
		"customer_id",
		"date_customer_reported",
		"decision",
		"dispute_documents",
		"disputed_amount",
		"id",
		"last_updated_time",
		"memo",
		"network",
		"payment_rail",
		"status",
		"tenant",
		"transaction_id",
		"action_history",
		"available_actions",
		"credit_status",
		"lifecycle_state",
		"managed_by",
		"network_eligibility",
		"reason_code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCardDisputeResponse := _CardDisputeResponse{}

	err = json.Unmarshal(data, &varCardDisputeResponse)

	if err != nil {
		return err
	}

	*o = CardDisputeResponse(varCardDisputeResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "applicable_regulation")
		delete(additionalProperties, "creation_time")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "customer_id")
		delete(additionalProperties, "date_customer_reported")
		delete(additionalProperties, "decision")
		delete(additionalProperties, "dispute_documents")
		delete(additionalProperties, "disputed_amount")
		delete(additionalProperties, "external_reference_id")
		delete(additionalProperties, "id")
		delete(additionalProperties, "last_action_by")
		delete(additionalProperties, "last_updated_time")
		delete(additionalProperties, "memo")
		delete(additionalProperties, "network")
		delete(additionalProperties, "payment_rail")
		delete(additionalProperties, "status")
		delete(additionalProperties, "tenant")
		delete(additionalProperties, "timestamp_final_decision")
		delete(additionalProperties, "timestamp_investigation_due")
		delete(additionalProperties, "timestamp_provisional_credit_due")
		delete(additionalProperties, "transaction_id")
		delete(additionalProperties, "acquirer_reference_number")
		delete(additionalProperties, "action_history")
		delete(additionalProperties, "available_actions")
		delete(additionalProperties, "credit_status")
		delete(additionalProperties, "lifecycle_state")
		delete(additionalProperties, "managed_by")
		delete(additionalProperties, "network_eligibility")
		delete(additionalProperties, "reason_code")
		delete(additionalProperties, "switch_serial_number")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCardDisputeResponse struct {
	value *CardDisputeResponse
	isSet bool
}

func (v NullableCardDisputeResponse) Get() *CardDisputeResponse {
	return v.value
}

func (v *NullableCardDisputeResponse) Set(val *CardDisputeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCardDisputeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCardDisputeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardDisputeResponse(val *CardDisputeResponse) *NullableCardDisputeResponse {
	return &NullableCardDisputeResponse{value: val, isSet: true}
}

func (v NullableCardDisputeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardDisputeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
