/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
)

// TransferStatus The status of the transfer
type TransferStatus string

// List of transfer_status
const (
	TRANSFERSTATUS_SUCCEEDED TransferStatus = "SUCCEEDED"
	TRANSFERSTATUS_PENDING   TransferStatus = "PENDING"
	TRANSFERSTATUS_DECLINED  TransferStatus = "DECLINED"
	TRANSFERSTATUS_CANCELED  TransferStatus = "CANCELED"
	TRANSFERSTATUS_UNKNOWN   TransferStatus = "UNKNOWN"
)

// All allowed values of TransferStatus enum
var AllowedTransferStatusEnumValues = []TransferStatus{
	"SUCCEEDED",
	"PENDING",
	"DECLINED",
	"CANCELED",
	"UNKNOWN",
}

func (v *TransferStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TransferStatus(value)
	for _, existing := range AllowedTransferStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TransferStatus", value)
}

// NewTransferStatusFromValue returns a pointer to a valid TransferStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTransferStatusFromValue(v string) (*TransferStatus, error) {
	ev := TransferStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TransferStatus: valid values are %v", v, AllowedTransferStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TransferStatus) IsValid() bool {
	for _, existing := range AllowedTransferStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to transfer_status value
func (v TransferStatus) Ptr() *TransferStatus {
	return &v
}

type NullableTransferStatus struct {
	value *TransferStatus
	isSet bool
}

func (v NullableTransferStatus) Get() *TransferStatus {
	return v.value
}

func (v *NullableTransferStatus) Set(val *TransferStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferStatus(val *TransferStatus) *NullableTransferStatus {
	return &NullableTransferStatus{value: val, isSet: true}
}

func (v NullableTransferStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
