/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
)

// checks if the FeePost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeePost{}

// FeePost struct for FeePost
type FeePost struct {
	// The ID of the business or customer account being charged the fee.
	AccountId string `json:"account_id"`
	// The amount of the fee in ISO 4217 minor currency units, e.g. cents. The internal account referenced by the fee template will be debited this amount. Defaults to the value in the fee template.
	Amount *int32 `json:"amount,omitempty"`
	// Optional field to store additional information about the resource. Intended to be used by the integrator to store non-sensitive data.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// An optional note for this instance of the fee.
	Note *string `json:"note,omitempty"`
	// An optional reference ID that uniquely identifies this fee instance. This ID will be included in the posted fee transaction.
	ReferenceId *string `json:"reference_id,omitempty"`
	// The ID of the fee template to use to create the fee. Values from the fee template will be used as defaults for the fee. Note that the fee template may have been updated since the fee was created and that such subsequent updates to the fee template do not affect existing fees.
	TemplateId           string `json:"template_id"`
	AdditionalProperties map[string]interface{}
}

type _FeePost FeePost

// NewFeePost instantiates a new FeePost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeePost(accountId string, templateId string) *FeePost {
	this := FeePost{}
	this.AccountId = accountId
	this.TemplateId = templateId
	return &this
}

// NewFeePostWithDefaults instantiates a new FeePost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeePostWithDefaults() *FeePost {
	this := FeePost{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *FeePost) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *FeePost) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *FeePost) SetAccountId(v string) {
	o.AccountId = v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *FeePost) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeePost) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *FeePost) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *FeePost) SetAmount(v int32) {
	o.Amount = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *FeePost) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeePost) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *FeePost) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *FeePost) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *FeePost) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeePost) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *FeePost) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *FeePost) SetNote(v string) {
	o.Note = &v
}

// GetReferenceId returns the ReferenceId field value if set, zero value otherwise.
func (o *FeePost) GetReferenceId() string {
	if o == nil || IsNil(o.ReferenceId) {
		var ret string
		return ret
	}
	return *o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeePost) GetReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReferenceId) {
		return nil, false
	}
	return o.ReferenceId, true
}

// HasReferenceId returns a boolean if a field has been set.
func (o *FeePost) HasReferenceId() bool {
	if o != nil && !IsNil(o.ReferenceId) {
		return true
	}

	return false
}

// SetReferenceId gets a reference to the given string and assigns it to the ReferenceId field.
func (o *FeePost) SetReferenceId(v string) {
	o.ReferenceId = &v
}

// GetTemplateId returns the TemplateId field value
func (o *FeePost) GetTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *FeePost) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *FeePost) SetTemplateId(v string) {
	o.TemplateId = v
}

func (o FeePost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeePost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.ReferenceId) {
		toSerialize["reference_id"] = o.ReferenceId
	}
	toSerialize["template_id"] = o.TemplateId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FeePost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"template_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFeePost := _FeePost{}

	err = json.Unmarshal(data, &varFeePost)

	if err != nil {
		return err
	}

	*o = FeePost(varFeePost)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "note")
		delete(additionalProperties, "reference_id")
		delete(additionalProperties, "template_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFeePost struct {
	value *FeePost
	isSet bool
}

func (v NullableFeePost) Get() *FeePost {
	return v.value
}

func (v *NullableFeePost) Set(val *FeePost) {
	v.value = val
	v.isSet = true
}

func (v NullableFeePost) IsSet() bool {
	return v.isSet
}

func (v *NullableFeePost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeePost(val *FeePost) *NullableFeePost {
	return &NullableFeePost{value: val, isSet: true}
}

func (v NullableFeePost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeePost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
