/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
)

// DeviceTypeResponse Type of the device where the Digital Wallet Token is used in
type DeviceTypeResponse string

// List of device_type_response
const (
	DEVICETYPERESPONSE_MOBILE_PHONE           DeviceTypeResponse = "MOBILE_PHONE"
	DEVICETYPERESPONSE_WATCH                  DeviceTypeResponse = "WATCH"
	DEVICETYPERESPONSE_TABLET                 DeviceTypeResponse = "TABLET"
	DEVICETYPERESPONSE_MOBILE_PHONE_OR_TABLET DeviceTypeResponse = "MOBILE_PHONE_OR_TABLET"
	DEVICETYPERESPONSE_VEHICLE                DeviceTypeResponse = "VEHICLE"
	DEVICETYPERESPONSE_APPLIANCE              DeviceTypeResponse = "APPLIANCE"
	DEVICETYPERESPONSE_LAPTOP                 DeviceTypeResponse = "LAPTOP"
	DEVICETYPERESPONSE_GAMING_DEVICE          DeviceTypeResponse = "GAMING_DEVICE"
	DEVICETYPERESPONSE_UNKNOWN_DEVICE         DeviceTypeResponse = "UNKNOWN_DEVICE"
)

// All allowed values of DeviceTypeResponse enum
var AllowedDeviceTypeResponseEnumValues = []DeviceTypeResponse{
	"MOBILE_PHONE",
	"WATCH",
	"TABLET",
	"MOBILE_PHONE_OR_TABLET",
	"VEHICLE",
	"APPLIANCE",
	"LAPTOP",
	"GAMING_DEVICE",
	"UNKNOWN_DEVICE",
}

func (v *DeviceTypeResponse) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DeviceTypeResponse(value)
	for _, existing := range AllowedDeviceTypeResponseEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DeviceTypeResponse", value)
}

// NewDeviceTypeResponseFromValue returns a pointer to a valid DeviceTypeResponse
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDeviceTypeResponseFromValue(v string) (*DeviceTypeResponse, error) {
	ev := DeviceTypeResponse(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DeviceTypeResponse: valid values are %v", v, AllowedDeviceTypeResponseEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DeviceTypeResponse) IsValid() bool {
	for _, existing := range AllowedDeviceTypeResponseEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to device_type_response value
func (v DeviceTypeResponse) Ptr() *DeviceTypeResponse {
	return &v
}

type NullableDeviceTypeResponse struct {
	value *DeviceTypeResponse
	isSet bool
}

func (v NullableDeviceTypeResponse) Get() *DeviceTypeResponse {
	return v.value
}

func (v *NullableDeviceTypeResponse) Set(val *DeviceTypeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceTypeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceTypeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceTypeResponse(val *DeviceTypeResponse) *NullableDeviceTypeResponse {
	return &NullableDeviceTypeResponse{value: val, isSet: true}
}

func (v NullableDeviceTypeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceTypeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
