/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ExternalCardResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExternalCardResponse{}

// ExternalCardResponse struct for ExternalCardResponse
type ExternalCardResponse struct {
	// Bank Identification Number
	Bin          *string    `json:"bin,omitempty"`
	CreationTime *time.Time `json:"creation_time,omitempty"`
	// ISO 4217  Alpha-3 currency code
	Currency string `json:"currency"`
	// Customer ID for the application
	CustomerId   string     `json:"customer_id"`
	DeletionTime *time.Time `json:"deletion_time,omitempty"`
	// Card expiration month
	ExpirationMonth string `json:"expiration_month"`
	// Card expiration year
	ExpirationYear string `json:"expiration_year"`
	// Unique identifier
	Id string `json:"id"`
	// Name of the issuing financial institution
	Issuer *string `json:"issuer,omitempty"`
	// The last four digits of the card PAN
	LastFour        string     `json:"last_four"`
	LastUpdatedTime *time.Time `json:"last_updated_time,omitempty"`
	// The cardholder name
	Name string `json:"name"`
	// A unique identifier associated with a specific cardholder PAN and its affiliated tokens
	PaymentAccountReference *string            `json:"payment_account_reference,omitempty"`
	Status                  ExternalCardStatus `json:"status"`
	// The id of the tenant containing the resource.
	Tenant               string                     `json:"tenant"`
	Verifications        *ExternalCardVerifications `json:"verifications,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ExternalCardResponse ExternalCardResponse

// NewExternalCardResponse instantiates a new ExternalCardResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalCardResponse(currency string, customerId string, expirationMonth string, expirationYear string, id string, lastFour string, name string, status ExternalCardStatus, tenant string) *ExternalCardResponse {
	this := ExternalCardResponse{}
	this.Currency = currency
	this.CustomerId = customerId
	this.ExpirationMonth = expirationMonth
	this.ExpirationYear = expirationYear
	this.Id = id
	this.LastFour = lastFour
	this.Name = name
	this.Status = status
	this.Tenant = tenant
	return &this
}

// NewExternalCardResponseWithDefaults instantiates a new ExternalCardResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalCardResponseWithDefaults() *ExternalCardResponse {
	this := ExternalCardResponse{}
	return &this
}

// GetBin returns the Bin field value if set, zero value otherwise.
func (o *ExternalCardResponse) GetBin() string {
	if o == nil || IsNil(o.Bin) {
		var ret string
		return ret
	}
	return *o.Bin
}

// GetBinOk returns a tuple with the Bin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetBinOk() (*string, bool) {
	if o == nil || IsNil(o.Bin) {
		return nil, false
	}
	return o.Bin, true
}

// HasBin returns a boolean if a field has been set.
func (o *ExternalCardResponse) HasBin() bool {
	if o != nil && !IsNil(o.Bin) {
		return true
	}

	return false
}

// SetBin gets a reference to the given string and assigns it to the Bin field.
func (o *ExternalCardResponse) SetBin(v string) {
	o.Bin = &v
}

// GetCreationTime returns the CreationTime field value if set, zero value otherwise.
func (o *ExternalCardResponse) GetCreationTime() time.Time {
	if o == nil || IsNil(o.CreationTime) {
		var ret time.Time
		return ret
	}
	return *o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetCreationTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreationTime) {
		return nil, false
	}
	return o.CreationTime, true
}

// HasCreationTime returns a boolean if a field has been set.
func (o *ExternalCardResponse) HasCreationTime() bool {
	if o != nil && !IsNil(o.CreationTime) {
		return true
	}

	return false
}

// SetCreationTime gets a reference to the given time.Time and assigns it to the CreationTime field.
func (o *ExternalCardResponse) SetCreationTime(v time.Time) {
	o.CreationTime = &v
}

// GetCurrency returns the Currency field value
func (o *ExternalCardResponse) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *ExternalCardResponse) SetCurrency(v string) {
	o.Currency = v
}

// GetCustomerId returns the CustomerId field value
func (o *ExternalCardResponse) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *ExternalCardResponse) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetDeletionTime returns the DeletionTime field value if set, zero value otherwise.
func (o *ExternalCardResponse) GetDeletionTime() time.Time {
	if o == nil || IsNil(o.DeletionTime) {
		var ret time.Time
		return ret
	}
	return *o.DeletionTime
}

// GetDeletionTimeOk returns a tuple with the DeletionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetDeletionTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletionTime) {
		return nil, false
	}
	return o.DeletionTime, true
}

// HasDeletionTime returns a boolean if a field has been set.
func (o *ExternalCardResponse) HasDeletionTime() bool {
	if o != nil && !IsNil(o.DeletionTime) {
		return true
	}

	return false
}

// SetDeletionTime gets a reference to the given time.Time and assigns it to the DeletionTime field.
func (o *ExternalCardResponse) SetDeletionTime(v time.Time) {
	o.DeletionTime = &v
}

// GetExpirationMonth returns the ExpirationMonth field value
func (o *ExternalCardResponse) GetExpirationMonth() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpirationMonth
}

// GetExpirationMonthOk returns a tuple with the ExpirationMonth field value
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetExpirationMonthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpirationMonth, true
}

// SetExpirationMonth sets field value
func (o *ExternalCardResponse) SetExpirationMonth(v string) {
	o.ExpirationMonth = v
}

// GetExpirationYear returns the ExpirationYear field value
func (o *ExternalCardResponse) GetExpirationYear() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpirationYear
}

// GetExpirationYearOk returns a tuple with the ExpirationYear field value
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetExpirationYearOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpirationYear, true
}

// SetExpirationYear sets field value
func (o *ExternalCardResponse) SetExpirationYear(v string) {
	o.ExpirationYear = v
}

// GetId returns the Id field value
func (o *ExternalCardResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ExternalCardResponse) SetId(v string) {
	o.Id = v
}

// GetIssuer returns the Issuer field value if set, zero value otherwise.
func (o *ExternalCardResponse) GetIssuer() string {
	if o == nil || IsNil(o.Issuer) {
		var ret string
		return ret
	}
	return *o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.Issuer) {
		return nil, false
	}
	return o.Issuer, true
}

// HasIssuer returns a boolean if a field has been set.
func (o *ExternalCardResponse) HasIssuer() bool {
	if o != nil && !IsNil(o.Issuer) {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given string and assigns it to the Issuer field.
func (o *ExternalCardResponse) SetIssuer(v string) {
	o.Issuer = &v
}

// GetLastFour returns the LastFour field value
func (o *ExternalCardResponse) GetLastFour() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastFour
}

// GetLastFourOk returns a tuple with the LastFour field value
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetLastFourOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastFour, true
}

// SetLastFour sets field value
func (o *ExternalCardResponse) SetLastFour(v string) {
	o.LastFour = v
}

// GetLastUpdatedTime returns the LastUpdatedTime field value if set, zero value otherwise.
func (o *ExternalCardResponse) GetLastUpdatedTime() time.Time {
	if o == nil || IsNil(o.LastUpdatedTime) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdatedTime
}

// GetLastUpdatedTimeOk returns a tuple with the LastUpdatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetLastUpdatedTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUpdatedTime) {
		return nil, false
	}
	return o.LastUpdatedTime, true
}

// HasLastUpdatedTime returns a boolean if a field has been set.
func (o *ExternalCardResponse) HasLastUpdatedTime() bool {
	if o != nil && !IsNil(o.LastUpdatedTime) {
		return true
	}

	return false
}

// SetLastUpdatedTime gets a reference to the given time.Time and assigns it to the LastUpdatedTime field.
func (o *ExternalCardResponse) SetLastUpdatedTime(v time.Time) {
	o.LastUpdatedTime = &v
}

// GetName returns the Name field value
func (o *ExternalCardResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ExternalCardResponse) SetName(v string) {
	o.Name = v
}

// GetPaymentAccountReference returns the PaymentAccountReference field value if set, zero value otherwise.
func (o *ExternalCardResponse) GetPaymentAccountReference() string {
	if o == nil || IsNil(o.PaymentAccountReference) {
		var ret string
		return ret
	}
	return *o.PaymentAccountReference
}

// GetPaymentAccountReferenceOk returns a tuple with the PaymentAccountReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetPaymentAccountReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentAccountReference) {
		return nil, false
	}
	return o.PaymentAccountReference, true
}

// HasPaymentAccountReference returns a boolean if a field has been set.
func (o *ExternalCardResponse) HasPaymentAccountReference() bool {
	if o != nil && !IsNil(o.PaymentAccountReference) {
		return true
	}

	return false
}

// SetPaymentAccountReference gets a reference to the given string and assigns it to the PaymentAccountReference field.
func (o *ExternalCardResponse) SetPaymentAccountReference(v string) {
	o.PaymentAccountReference = &v
}

// GetStatus returns the Status field value
func (o *ExternalCardResponse) GetStatus() ExternalCardStatus {
	if o == nil {
		var ret ExternalCardStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetStatusOk() (*ExternalCardStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ExternalCardResponse) SetStatus(v ExternalCardStatus) {
	o.Status = v
}

// GetTenant returns the Tenant field value
func (o *ExternalCardResponse) GetTenant() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetTenantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tenant, true
}

// SetTenant sets field value
func (o *ExternalCardResponse) SetTenant(v string) {
	o.Tenant = v
}

// GetVerifications returns the Verifications field value if set, zero value otherwise.
func (o *ExternalCardResponse) GetVerifications() ExternalCardVerifications {
	if o == nil || IsNil(o.Verifications) {
		var ret ExternalCardVerifications
		return ret
	}
	return *o.Verifications
}

// GetVerificationsOk returns a tuple with the Verifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalCardResponse) GetVerificationsOk() (*ExternalCardVerifications, bool) {
	if o == nil || IsNil(o.Verifications) {
		return nil, false
	}
	return o.Verifications, true
}

// HasVerifications returns a boolean if a field has been set.
func (o *ExternalCardResponse) HasVerifications() bool {
	if o != nil && !IsNil(o.Verifications) {
		return true
	}

	return false
}

// SetVerifications gets a reference to the given ExternalCardVerifications and assigns it to the Verifications field.
func (o *ExternalCardResponse) SetVerifications(v ExternalCardVerifications) {
	o.Verifications = &v
}

func (o ExternalCardResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExternalCardResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bin) {
		toSerialize["bin"] = o.Bin
	}
	if !IsNil(o.CreationTime) {
		toSerialize["creation_time"] = o.CreationTime
	}
	toSerialize["currency"] = o.Currency
	toSerialize["customer_id"] = o.CustomerId
	if !IsNil(o.DeletionTime) {
		toSerialize["deletion_time"] = o.DeletionTime
	}
	toSerialize["expiration_month"] = o.ExpirationMonth
	toSerialize["expiration_year"] = o.ExpirationYear
	toSerialize["id"] = o.Id
	if !IsNil(o.Issuer) {
		toSerialize["issuer"] = o.Issuer
	}
	toSerialize["last_four"] = o.LastFour
	if !IsNil(o.LastUpdatedTime) {
		toSerialize["last_updated_time"] = o.LastUpdatedTime
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.PaymentAccountReference) {
		toSerialize["payment_account_reference"] = o.PaymentAccountReference
	}
	toSerialize["status"] = o.Status
	toSerialize["tenant"] = o.Tenant
	if !IsNil(o.Verifications) {
		toSerialize["verifications"] = o.Verifications
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ExternalCardResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currency",
		"customer_id",
		"expiration_month",
		"expiration_year",
		"id",
		"last_four",
		"name",
		"status",
		"tenant",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExternalCardResponse := _ExternalCardResponse{}

	err = json.Unmarshal(data, &varExternalCardResponse)

	if err != nil {
		return err
	}

	*o = ExternalCardResponse(varExternalCardResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bin")
		delete(additionalProperties, "creation_time")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "customer_id")
		delete(additionalProperties, "deletion_time")
		delete(additionalProperties, "expiration_month")
		delete(additionalProperties, "expiration_year")
		delete(additionalProperties, "id")
		delete(additionalProperties, "issuer")
		delete(additionalProperties, "last_four")
		delete(additionalProperties, "last_updated_time")
		delete(additionalProperties, "name")
		delete(additionalProperties, "payment_account_reference")
		delete(additionalProperties, "status")
		delete(additionalProperties, "tenant")
		delete(additionalProperties, "verifications")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExternalCardResponse struct {
	value *ExternalCardResponse
	isSet bool
}

func (v NullableExternalCardResponse) Get() *ExternalCardResponse {
	return v.value
}

func (v *NullableExternalCardResponse) Set(val *ExternalCardResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalCardResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalCardResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalCardResponse(val *ExternalCardResponse) *NullableExternalCardResponse {
	return &NullableExternalCardResponse{value: val, isSet: true}
}

func (v NullableExternalCardResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalCardResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
