/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
)

// SpendControlTimeRangeType the model 'SpendControlTimeRangeType'
type SpendControlTimeRangeType string

// List of spend_control_time_range_type
const (
	SPENDCONTROLTIMERANGETYPE_ROLLING_WINDOW_DAYS SpendControlTimeRangeType = "ROLLING_WINDOW_DAYS"
	SPENDCONTROLTIMERANGETYPE_SINGLE_TRANSACTION  SpendControlTimeRangeType = "SINGLE_TRANSACTION"
	SPENDCONTROLTIMERANGETYPE_STATIC_WINDOW       SpendControlTimeRangeType = "STATIC_WINDOW"
	SPENDCONTROLTIMERANGETYPE_ROLLING_WINDOW      SpendControlTimeRangeType = "ROLLING_WINDOW"
	SPENDCONTROLTIMERANGETYPE_FOREVER             SpendControlTimeRangeType = "FOREVER"
)

// All allowed values of SpendControlTimeRangeType enum
var AllowedSpendControlTimeRangeTypeEnumValues = []SpendControlTimeRangeType{
	"ROLLING_WINDOW_DAYS",
	"SINGLE_TRANSACTION",
	"STATIC_WINDOW",
	"ROLLING_WINDOW",
	"FOREVER",
}

func (v *SpendControlTimeRangeType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SpendControlTimeRangeType(value)
	for _, existing := range AllowedSpendControlTimeRangeTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SpendControlTimeRangeType", value)
}

// NewSpendControlTimeRangeTypeFromValue returns a pointer to a valid SpendControlTimeRangeType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSpendControlTimeRangeTypeFromValue(v string) (*SpendControlTimeRangeType, error) {
	ev := SpendControlTimeRangeType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SpendControlTimeRangeType: valid values are %v", v, AllowedSpendControlTimeRangeTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SpendControlTimeRangeType) IsValid() bool {
	for _, existing := range AllowedSpendControlTimeRangeTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to spend_control_time_range_type value
func (v SpendControlTimeRangeType) Ptr() *SpendControlTimeRangeType {
	return &v
}

type NullableSpendControlTimeRangeType struct {
	value *SpendControlTimeRangeType
	isSet bool
}

func (v NullableSpendControlTimeRangeType) Get() *SpendControlTimeRangeType {
	return v.value
}

func (v *NullableSpendControlTimeRangeType) Set(val *SpendControlTimeRangeType) {
	v.value = val
	v.isSet = true
}

func (v NullableSpendControlTimeRangeType) IsSet() bool {
	return v.isSet
}

func (v *NullableSpendControlTimeRangeType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpendControlTimeRangeType(val *SpendControlTimeRangeType) *NullableSpendControlTimeRangeType {
	return &NullableSpendControlTimeRangeType{value: val, isSet: true}
}

func (v NullableSpendControlTimeRangeType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpendControlTimeRangeType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
