/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
)

// checks if the DocumentVerificationSessionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentVerificationSessionResponse{}

// DocumentVerificationSessionResponse struct for DocumentVerificationSessionResponse
type DocumentVerificationSessionResponse struct {
	// ID of the document verification session to be used in `/verifications/verify` request.
	SessionToken *string `json:"session_token,omitempty"`
	// URL of the document verification session which can be shared with the end-customer.
	Url                  *string `json:"url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DocumentVerificationSessionResponse DocumentVerificationSessionResponse

// NewDocumentVerificationSessionResponse instantiates a new DocumentVerificationSessionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentVerificationSessionResponse() *DocumentVerificationSessionResponse {
	this := DocumentVerificationSessionResponse{}
	return &this
}

// NewDocumentVerificationSessionResponseWithDefaults instantiates a new DocumentVerificationSessionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentVerificationSessionResponseWithDefaults() *DocumentVerificationSessionResponse {
	this := DocumentVerificationSessionResponse{}
	return &this
}

// GetSessionToken returns the SessionToken field value if set, zero value otherwise.
func (o *DocumentVerificationSessionResponse) GetSessionToken() string {
	if o == nil || IsNil(o.SessionToken) {
		var ret string
		return ret
	}
	return *o.SessionToken
}

// GetSessionTokenOk returns a tuple with the SessionToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentVerificationSessionResponse) GetSessionTokenOk() (*string, bool) {
	if o == nil || IsNil(o.SessionToken) {
		return nil, false
	}
	return o.SessionToken, true
}

// HasSessionToken returns a boolean if a field has been set.
func (o *DocumentVerificationSessionResponse) HasSessionToken() bool {
	if o != nil && !IsNil(o.SessionToken) {
		return true
	}

	return false
}

// SetSessionToken gets a reference to the given string and assigns it to the SessionToken field.
func (o *DocumentVerificationSessionResponse) SetSessionToken(v string) {
	o.SessionToken = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *DocumentVerificationSessionResponse) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentVerificationSessionResponse) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *DocumentVerificationSessionResponse) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *DocumentVerificationSessionResponse) SetUrl(v string) {
	o.Url = &v
}

func (o DocumentVerificationSessionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentVerificationSessionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SessionToken) {
		toSerialize["session_token"] = o.SessionToken
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DocumentVerificationSessionResponse) UnmarshalJSON(data []byte) (err error) {
	varDocumentVerificationSessionResponse := _DocumentVerificationSessionResponse{}

	err = json.Unmarshal(data, &varDocumentVerificationSessionResponse)

	if err != nil {
		return err
	}

	*o = DocumentVerificationSessionResponse(varDocumentVerificationSessionResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "session_token")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDocumentVerificationSessionResponse struct {
	value *DocumentVerificationSessionResponse
	isSet bool
}

func (v NullableDocumentVerificationSessionResponse) Get() *DocumentVerificationSessionResponse {
	return v.value
}

func (v *NullableDocumentVerificationSessionResponse) Set(val *DocumentVerificationSessionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentVerificationSessionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentVerificationSessionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentVerificationSessionResponse(val *DocumentVerificationSessionResponse) *NullableDocumentVerificationSessionResponse {
	return &NullableDocumentVerificationSessionResponse{value: val, isSet: true}
}

func (v NullableDocumentVerificationSessionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentVerificationSessionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
