/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"fmt"
)

// checks if the PartyLoanproVendorData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartyLoanproVendorData{}

// PartyLoanproVendorData LoanPro-specific vendor data
type PartyLoanproVendorData struct {
	// LoanPro customer ID
	CustomerId           int64 `json:"customer_id"`
	AdditionalProperties map[string]interface{}
}

type _PartyLoanproVendorData PartyLoanproVendorData

// NewPartyLoanproVendorData instantiates a new PartyLoanproVendorData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartyLoanproVendorData(customerId int64) *PartyLoanproVendorData {
	this := PartyLoanproVendorData{}
	this.CustomerId = customerId
	return &this
}

// NewPartyLoanproVendorDataWithDefaults instantiates a new PartyLoanproVendorData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartyLoanproVendorDataWithDefaults() *PartyLoanproVendorData {
	this := PartyLoanproVendorData{}
	return &this
}

// GetCustomerId returns the CustomerId field value
func (o *PartyLoanproVendorData) GetCustomerId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *PartyLoanproVendorData) GetCustomerIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *PartyLoanproVendorData) SetCustomerId(v int64) {
	o.CustomerId = v
}

func (o PartyLoanproVendorData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartyLoanproVendorData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customer_id"] = o.CustomerId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PartyLoanproVendorData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customer_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartyLoanproVendorData := _PartyLoanproVendorData{}

	err = json.Unmarshal(data, &varPartyLoanproVendorData)

	if err != nil {
		return err
	}

	*o = PartyLoanproVendorData(varPartyLoanproVendorData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "customer_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePartyLoanproVendorData struct {
	value *PartyLoanproVendorData
	isSet bool
}

func (v NullablePartyLoanproVendorData) Get() *PartyLoanproVendorData {
	return v.value
}

func (v *NullablePartyLoanproVendorData) Set(val *PartyLoanproVendorData) {
	v.value = val
	v.isSet = true
}

func (v NullablePartyLoanproVendorData) IsSet() bool {
	return v.isSet
}

func (v *NullablePartyLoanproVendorData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartyLoanproVendorData(val *PartyLoanproVendorData) *NullablePartyLoanproVendorData {
	return &NullablePartyLoanproVendorData{value: val, isSet: true}
}

func (v NullablePartyLoanproVendorData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartyLoanproVendorData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
